import capitalize from "lodash.capitalize";

const cleanAlaskaAirlinesOperatingName = (airlineName) => {
  const alaskaRegex = /^(?<airline>[\s\w]*)\s+as\s+(?<dbaPart1>alaska)(?<dbaPart2>[a-z]{1,20})$/i;
  let cleanedName = airlineName;
  if (alaskaRegex.test(cleanedName)) {
    const nameGroups = cleanedName.match(alaskaRegex);
    cleanedName = `${nameGroups.groups.airline} as ${nameGroups.groups.dbaPart1} ${capitalize(
      nameGroups.groups.dbaPart2,
    )}`;
  }
  return cleanedName;
};

const AirlineMap = {
  airlineDetailsMap: {
    ANA: { name: "ANA", color: "#254897", code: "NH", alliance: "Star Alliance" },
    "ANA (All Nippon Airways)": { name: "ANA", color: "#0f4a8d", alliance: "Star Alliance" },
    "ANA Airlines": { name: "ANA", color: "#254897", code: "NH", alliance: "Star Alliance" },
    "All Nippon Airways": { name: "ANA", color: "#254897", code: "NH", alliance: "Star Alliance" },
    Adria: { name: "Adria", color: "#2b438f", code: "JP", alliance: "Star Alliance" },
    "Adria Airways": { name: "Adria", color: "#2b438f", code: "JP", alliance: "Star Alliance" },
    Aegean: { name: "Aegean", color: "#94A4D4", code: "A3", alliance: "Star Alliance" },
    "Aegean Airlines": { name: "Aegean", color: "#94A4D4", code: "A3", alliance: "Star Alliance" },
    "Aer Lingus": { name: "Aer Lingus", color: "#008274", code: "EI", alliance: undefined },
    Aeroflot: { name: "Aeroflot", color: "#3C72A8", code: "SU", alliance: "SkyTeam" },
    "Aeroflot-Russian Airlines": { name: "Aeroflot", color: "#3C72A8", code: "SU", alliance: "SkyTeam" },
    Aerolineas: { name: "Aerolineas", color: "#007ac2", code: "AR", alliance: "SkyTeam" },
    "Aerolineas Argentinas": { name: "Aerolineas", color: "#007ac2", code: "AR", alliance: "SkyTeam" },
    Aeroméxico: { name: "Aeromexico", color: "#000000", code: "AM", alliance: "SkyTeam" },
    Aeromexico: { name: "Aeromexico", color: "#000000", code: "AM", alliance: "SkyTeam" },
    AirAsia: { name: "AirAsia", color: "#E32526", code: "AK", alliance: undefined },
    "Air Asia": { name: "AirAsia", color: "#E32526", code: "AK", alliance: undefined },
    AIRASIA: { name: "AirAsia", color: "#E32526", code: "AK", alliance: undefined },
    Aircalin: { name: "Aircalin", color: "#F44B24", code: "SB", alliance: undefined },
    "Air Arabia": { name: "Air Arabia", color: "#FC0444", code: "G9", alliance: undefined },
    "Air Astana": { name: "Air Astana", color: "#A48C64", code: "KC", alliance: undefined },
    "Air Austral": { name: "Air Austral", color: "#26b5e3", code: "UU", alliance: "Vanilla Alliance" },
    "Air Baltic": { name: "airBaltic", color: "#D3EB3B", code: "BT", alliance: undefined },
    Airbaltic: { name: "airBaltic", color: "#D3EB3B", code: "BT", alliance: undefined },
    AirBaltic: { name: "airBaltic", color: "#D3EB3B", code: "BT", alliance: undefined },
    airBaltic: { name: "airBaltic", color: "#D3EB3B", code: "BT", alliance: undefined },
    "Air Belgium": { name: "Air Belgium", color: "#F43444", code: "KF", alliance: undefined },
    "Air Canada": { name: "Air Canada", color: "#E53222", code: "AC", alliance: "Star Alliance" },
    "Air Caraibes": { name: "Air Caraibes", color: "#75C141", code: "TX", alliance: undefined },
    "Air China": { name: "Air China", color: "#DF524B", code: "CA", alliance: "Star Alliance" },
    "Air Corsica": { name: "Air Corsica", color: "#048CCC", code: "XK", alliance: undefined },
    "Air Dolomiti": { name: "Air Dolomiti", color: "#008e8f", code: "EN", alliance: undefined },
    "Air Europa": { name: "Air Europa", color: "#0474CC", code: "UX", alliance: "SkyTeam" },
    "Air France": { name: "Air France", color: "#DB3832", code: "AF", alliance: "SkyTeam" },
    "Air India": { name: "Air India", color: "#D47346", code: "AI", alliance: "Star Alliance" },
    "Air India Limited": { name: "Air India", color: "#D47346", code: "AI", alliance: "Star Alliance" },
    "Air Macau": { name: "Air Macau", color: "#342464", code: "NX", alliance: undefined },
    "Air Madagascar": { name: "Air Madagascar", color: "#8C0424", code: "MD", alliance: "Vanilla Alliance" },
    "Air Malta": { name: "Air Malta", color: "#e77027", code: "KM", alliance: undefined },
    "Air Mauritius": { name: "Air Mauritius", color: "#C4042C", code: "MK", alliance: "Vanilla Alliance" },
    "Air Namibia": { name: "Air Namibia", color: "#FBF304", code: "SW", alliance: undefined },
    "Air New Zealand": { name: "Air New Zealand", color: "#241C24", code: "NZ", alliance: "Star Alliance" },
    "Air North": { name: "Air North", color: "#F47B20", code: "4N", alliance: undefined },
    "Air Seoul": { name: "Air Seoul", color: "#048B7B", code: "RS", alliance: "Star Alliance" },
    "Air Serbia": { name: "Air Serbia", color: "#0C4484", code: "JU", alliance: undefined },
    "Air Seychelles": { name: "Air Seychelles", color: "#9DC943", code: "HM", alliance: "Vanilla Alliance" },
    "Air Tahiti Nui": { name: "Air Tahiti Nui", color: "#2CCCD4", code: "TN", alliance: undefined },
    "Air Transat": { name: "Air Transat", color: "#3CBCEC", code: "TS", alliance: undefined },
    "Air Vanuatu": { name: "Air Vanuatu", color: "#009543", code: "NF", alliance: undefined },
    "Air Vistara": { name: "Vistara", color: "#47143D", code: "UK", alliance: undefined },
    Airlink: { name: "Airlink", color: "#E4AE5C", code: "4Z", alliance: undefined },
    "South African Airlink": { name: "Airlink", color: "#E4AE5C", code: "4Z", alliance: undefined },
    Alaska: { name: "Alaska", color: "#51172C", code: "AS", alliance: "Oneworld" },
    "Alaska Airlines": { name: "Alaska", color: "#51172C", code: "AS", alliance: "Oneworld" },
    Alitilia: { name: "ITA Airways", color: "#04643C", code: "AZ", alliance: "SkyTeam" },
    "ITA Airways": { name: "ITA Airways", color: "#04643C", code: "AZ", alliance: "SkyTeam" },
    "ITA - Italia Trasporto Aereo": { name: "ITA Airways", color: "#04643C", code: "AZ", alliance: "SkyTeam" },
    Allegiant: { name: "Allegiant", color: "#FBCE21", code: "G4", alliance: undefined },
    "Allegiant Air": { name: "Allegiant", color: "#FBCE21", code: "G4", alliance: undefined },
    American: { name: "American", color: "#C5423E", code: "AA", alliance: "Oneworld" },
    "American Airlines": { name: "American", color: "#C5423E", code: "AA", alliance: "Oneworld" },
    ASKY: { name: "ASKY", color: "#340C04", code: "KP", alliance: undefined },
    "ASKY Airlines": { name: "ASKY", color: "#340C04", code: "KP", alliance: undefined },
    "Asky Airlines": { name: "ASKY", color: "#340C04", code: "KP", alliance: undefined },
    Austrian: { name: "Austrian", color: "#D41C04", code: "OS", alliance: "Star Alliance" },
    "Austrian Airlines": { name: "Austrian", color: "#D41C04", code: "OS", alliance: "Star Alliance" },
    Asiana: { name: "Asiana", color: "#FC0404", code: "OZ", alliance: "Star Alliance" },
    "Asiana Air": { name: "Asiana", color: "#FC0404", code: "OZ", alliance: "Star Alliance" },
    "Asiana Airlines": { name: "Asiana", color: "#FC0404", code: "OZ", alliance: "Star Alliance" },
    Avianca: { name: "Avianca", color: "#DA291C", code: "AV", alliance: "Star Alliance" },
    TACA: { name: "Avianca", color: "#DA291C", code: "AV", alliance: "Star Alliance" },
    Azerbaijan: { name: "Azerbaijan", color: "#7CCCE4", code: "J2", alliance: undefined },
    "Azerbaijan Airlines": { name: "Azerbaijan", color: "#7CCCE4", code: "J2", alliance: undefined },
    Azul: { name: "Azul Brazilian", color: "#6ca9db", code: "AD", alliance: undefined },
    "Azul Linhas Aereas Brasileiras": { name: "Azul Brazilian", color: "#6ca9db", code: "AD", alliance: undefined },
    Bamboo: { name: "Bamboo", color: "#64AC53", code: "QH", alliance: undefined },
    "Bamboo Airways": { name: "Bamboo", color: "#64AC53", code: "QH", alliance: undefined },
    Bangkok: { name: "Bangkok Airways", color: "#BC9454", code: "PG", alliance: undefined },
    "Bangkok Airways": { name: "Bangkok Airways", color: "#BC9454", code: "PG", alliance: undefined },
    Breeze: { name: "Breeze", color: "#ABC3EB", code: "MX", alliance: undefined },
    "Breeze Airways": { name: "Breeze", color: "#ABC3EB", code: "MX", alliance: undefined },
    British: { name: "British", color: "#EA8E8C", code: "BA", alliance: "Oneworld" },
    "British Airways": { name: "British", color: "#EA8E8C", code: "BA", alliance: "Oneworld" },
    Brussels: { name: "Brussels", color: "#EE452A", code: "SN", alliance: "Star Alliance" },
    "Brussels Airlines": { name: "Brussels", color: "#EE452A", code: "SN", alliance: "Star Alliance" },
    Carribean: { name: "Carribean", color: "#C759A2", code: "BW", alliance: undefined },
    "Carribean Airlines": { name: "Carribean", color: "#C759A2", code: "BW", alliance: undefined },
    "Cathay Dragon": { name: "Cathay Dragon", color: "#E70013", code: "KA", alliance: "Oneworld" },
    Cathay: { name: "Cathay Pacific", color: "#00645A", code: "CX", alliance: "Oneworld" },
    "Cathay Pacific": { name: "Cathay Pacific", color: "#00645A", code: "CX", alliance: "Oneworld" },
    Cayman: { name: "Cayman Airways", color: "#43932C", code: "KX", alliance: undefined },
    "Cayman Airways": { name: "Cayman Airways", color: "#43932C", code: "KX", alliance: undefined },
    Cebu: { name: "Cebu Pacific", color: "#049484", code: "5J", alliance: "Value Alliance" },
    CEBU: { name: "Cebu Pacific", color: "#049484", code: "5J", alliance: "Value Alliance" },
    "Cebu Pacific": { name: "Cebu Pacific", color: "#049484", code: "5J", alliance: "Value Alliance" },
    "Cebu Pacific Air": { name: "Cebu Pacific", color: "#049484", code: "5J", alliance: "Value Alliance" },
    CemAir: { name: "CemAir", code: "5Z", color: "#BC343C", alliance: undefined },
    "Cem Air": { name: "CemAir", code: "5Z", color: "#BC343C", alliance: undefined },
    "China Airlines": { name: "China Airlines", color: "#DAABB1", code: "CI", alliance: "SkyTeam" },
    "China Eastern": { name: "China Eastern", color: "#A9545F", code: "MU", alliance: "SkyTeam" },
    "China Eastern Airlines": { name: "China Eastern", color: "#A9545F", code: "MU", alliance: "SkyTeam" },
    "China Southern": { name: "China Southern", color: "#93ACCA", code: "CZ", alliance: undefined },
    "China Southern Airlines": { name: "China Southern", color: "#93ACCA", code: "CZ", alliance: undefined },
    Condor: { name: "Condor", color: "#FBAB18", code: "DE", alliance: undefined },
    "Condor Air": { name: "Condor", color: "#FBAB18", code: "DE", alliance: undefined },
    "Condor Airlines": { name: "Condor", color: "#FBAB18", code: "DE", alliance: undefined },
    Copa: { name: "Copa", color: "#0060a9", code: "CM", alliance: "Star Alliance" },
    "Copa Airlines": { name: "Copa", color: "#0060a9", code: "CM", alliance: "Star Alliance" },
    Croatia: { name: "Croatia Airlines", color: "#EC3C34", code: "OU", alliance: "Star Alliance" },
    "Croatia Airlines": { name: "Croatia Airlines", color: "#EC3C34", code: "OU", alliance: "Star Alliance" },
    CSA: { name: "Copa", color: "#EC041C", code: "OK", alliance: "SkyTeam" },
    Czech: { name: "Copa", color: "#EC041C", code: "OK", alliance: "SkyTeam" },
    "Czech Airlines": { name: "Copa", color: "#EC041C", code: "OK", alliance: "SkyTeam" },
    Delta: { name: "Delta", color: "#EE722E", code: "DL", alliance: "SkyTeam" },
    "Delta Air Lines": { name: "Delta", color: "#EE722E", code: "DL", alliance: "SkyTeam" },
    easyJet: { name: "easyJet", color: "#ff6600", code: "EC", alliance: undefined },
    EasyJet: { name: "easyJet", color: "#ff6600", code: "EC", alliance: undefined },
    Easyjet: { name: "easyJet", color: "#ff6600", code: "EC", alliance: undefined },
    "easyJet Europe": { name: "easyJet", color: "#ff6600", code: "EC", alliance: undefined },
    Edelweiss: { name: "Edelweiss", color: "#F6E80F", code: "WK", alliance: undefined },
    "Edelweiss Air": { name: "Edelweiss", color: "#F6E80F", code: "WK", alliance: undefined },
    EGYPTAIR: { name: "Egyptair", color: "#00265d", code: "MS", alliance: "Star Alliance" },
    EgyptAir: { name: "Egyptair", color: "#00265d", code: "MS", alliance: "Star Alliance" },
    Egyptair: { name: "Egyptair", color: "#00265d", code: "MS", alliance: "Star Alliance" },
    "Egypt Air": { name: "Egyptair", color: "#00265d", code: "MS", alliance: "Star Alliance" },
    "El Al": { name: "El Al", color: "#041444", code: "LY", alliance: undefined },
    Emirates: { name: "Emirates", color: "#D71A21", code: "EK", alliance: undefined },
    "Emirates Airline": { name: "Emirates", color: "#CF534F", code: "EK", alliance: undefined },
    "Emirates Airlines": { name: "Emirates", color: "#CF534F", code: "EK", alliance: undefined },
    Ethiopian: { name: "Ethiopian", color: "#548C44", code: "ET", alliance: "Star Alliance" },
    "Ethiopian Air": { name: "Ethiopian", color: "#548C44", code: "ET", alliance: "Star Alliance" },
    "Ethiopian Airlines": { name: "Ethiopian", color: "#548C44", code: "ET", alliance: "Star Alliance" },
    "Etihad Airways": { name: "Etihad Airways", color: "#251019", code: "EY", alliance: undefined },
    Eurowings: { name: "Eurowings", color: "#8F174F", code: "EW", alliance: undefined },
    EVA: { name: "EVA", color: "#6F9F64", code: "BR", alliance: "Star Alliance" },
    "EVA Air": { name: "EVA", color: "#6F9F64", code: "BR", alliance: "Star Alliance" },
    "EVA Airways": { name: "EVA", color: "#6F9F64", code: "BR", alliance: "Star Alliance" },
    Fiji: { name: "Fiji Airways", color: "#2C1C14", code: "FJ", alliance: "Oneworld" },
    "Fiji Airways": { name: "Fiji Airways", color: "#2C1C14", code: "FJ", alliance: "Oneworld" },
    Finnair: { name: "Finnair", color: "#7F1F89", code: "AY", alliance: "Oneworld" },
    flydubai: { name: "flydubai", color: "#FF8200", code: "FZ", alliance: undefined },
    Flydubai: { name: "flydubai", color: "#FF8200", code: "FZ", alliance: undefined },
    FlyDubai: { name: "flydubai", color: "#FF8200", code: "FZ", alliance: undefined },
    FlyOne: { name: "FlyOne", color: "#0494DC", code: "5F", alliance: undefined },
    "French bee": { name: "French Bee", color: "#04A4E3", code: "BF", alliance: undefined },
    "French Bee": { name: "French Bee", color: "#04A4E3", code: "BF", alliance: undefined },
    "French Bee SAS": { name: "French Bee", color: "#04A4E3", code: "BF", alliance: undefined },
    Frontier: { name: "Frontier", color: "#378055", code: "F9", alliance: undefined },
    "Frontier Airlines": { name: "Frontier", color: "#378055", code: "F9", alliance: undefined },
    Garuda: { name: "Garuda Indonesia", color: "#047C94", code: "GA", alliance: "SkyTeam" },
    "Garuda Indonesia": { name: "Garuda Indonesia", color: "#047C94", code: "GA", alliance: "SkyTeam" },
    Gol: { name: "GOL", color: "#FC7423", code: "G3", alliance: undefined },
    GOL: { name: "GOL", color: "#FC7423", code: "G3", alliance: undefined },
    "GOL Linhas Aereas Inteligentes": { name: "GOL", color: "#FC7423", code: "G3", alliance: undefined },
    Gulf: { name: "Gulf Air", color: "#B4A483", code: "GF", alliance: undefined },
    "Gulf Air": { name: "Gulf Air", color: "#B4A483", code: "GF", alliance: undefined },
    Hainan: { name: "Hainan", color: "#e60012", code: "HU", alliance: undefined },
    "Hainan Airlines": { name: "Hainan", color: "#e60012", code: "HU", alliance: undefined },
    Hawaiian: { name: "Hawaiian", color: "#4D388A", code: "HA", alliance: undefined },
    "Hawaiian Airlines": { name: "Hawaiian", color: "#4D388A", code: "HA", alliance: undefined },
    Helvetic: { name: "Helvetic", color: "#E4241C", code: "2L", alliance: undefined },
    "Helvetic Airlines": { name: "Helvetic", color: "#E4241C", code: "2L", alliance: undefined },
    "Hong Kong Express": { name: "Hong Kong Express", color: "#6C2C94", code: "UO", alliance: "Oneworld" },
    "HK Express": { name: "Hong Kong Express", color: "#6C2C94", code: "UO", alliance: "Oneworld" },
    "Hong Kong Airlines": { name: "Hong Kong Airlines", color: "#E40414", code: "HX", alliance: undefined },
    Iberia: { name: "Iberia", color: "#D05653", code: "IB", alliance: "Oneworld" },
    IBERIA: { name: "Iberia", color: "#D05653", code: "IB", alliance: "Oneworld" },
    "Iberia Airlines": { name: "Iberia", color: "#D05653", code: "IB", alliance: "Oneworld" },
    Icelandair: { name: "Icelandair", color: "#043C84", code: "FI", alliance: undefined },
    IndiGo: { name: "IndiGo", color: "#3A469D", code: "6E", alliance: undefined },
    "IndiGo Airlines": { name: "IndiGo", color: "#3A469D", code: "6E", alliance: undefined },
    Indigo: { name: "IndiGo", color: "#3A469D", code: "6E", alliance: undefined },
    Interjet: { name: "InterJet", color: "#A8A8A8", code: "4O", alliance: undefined },
    InterJet: { name: "InterJet", color: "#A8A8A8", code: "4O", alliance: undefined },
    Japan: { name: "Japan Airlines", color: "#E56E69", code: "JL", alliance: "Oneworld" },
    "Japan Airlines": { name: "Japan Airlines", color: "#E56E69", code: "JL", alliance: "Oneworld" },
    Jeju: { name: "Jeju", color: "#F45424", code: "7C", alliance: "Value Alliance" },
    "Jeju Air": { name: "Jeju", color: "#F45424", code: "7C", alliance: "Value Alliance" },
    Jazeera: { name: "Jazeera Airways", color: "#1484C4", code: "J9", alliance: undefined },
    "Jazeera Airways": { name: "Jazeera Airways", color: "#1484C4", code: "J9", alliance: undefined },
    jet2: { name: "Jet2", color: "#e2231a", code: "LS", alliance: undefined },
    Jet2: { name: "Jet2", color: "#e2231a", code: "LS", alliance: undefined },
    jetBlue: { name: "jetBlue", color: "#5F90C8", code: "B6", alliance: undefined },
    JetBlue: { name: "jetBlue", color: "#5F90C8", code: "B6", alliance: undefined },
    "JetBlue Airways": { name: "jetBlue", color: "#5F90C8", code: "B6", alliance: undefined },
    Jetblue: { name: "jetBlue", color: "#5F90C8", code: "B6", alliance: undefined },
    "Jetblue Airways": { name: "jetBlue", color: "#5F90C8", code: "B6", alliance: undefined },
    Jetstar: { name: "Jetstar", color: "#FE5816", code: "JQ", alliance: undefined },
    JetStar: { name: "Jetstar", color: "#FE5816", code: "JQ", alliance: undefined },
    "Jetstar Airways": { name: "Jetstar", color: "#FE5816", code: "JQ", alliance: undefined },
    Jin: { name: "Jin Air", color: "#641C44", code: "LJ", alliance: undefined },
    "Jin Air": { name: "Jin Air", color: "#641C44", code: "LJ", alliance: undefined },
    JinAir: { name: "Jin Air", color: "#641C44", code: "LJ", alliance: undefined },
    JINAIR: { name: "Jin Air", color: "#641C44", code: "LJ", alliance: undefined },
    Kenya: { name: "Kenya", color: "#ec2227", code: "KQ", alliance: "SkyTeam" },
    "Kenya Airways": { name: "Kenya", color: "#ec2227", code: "KQ", alliance: "SkyTeam" },
    KLM: { name: "KLM", color: "#44A0DC", code: "KL", alliance: "SkyTeam" },
    "KLM Royal Dutch": { name: "KLM", color: "#44A0DC", code: "KL", alliance: "SkyTeam" },
    "KLM Royal Dutch Airlines": { name: "KLM", color: "#44A0DC", code: "KL", alliance: "SkyTeam" },
    "KLM-Royal Dutch Airlines": { name: "KLM", color: "#44A0DC", code: "KL", alliance: "SkyTeam" },
    Korean: { name: "Korean Air", color: "#154D9E", code: "KE", alliance: "SkyTeam" },
    "Korean Air": { name: "Korean Air", color: "#154D9E", code: "KE", alliance: "SkyTeam" },
    Kulula: { name: "Kulula", color: "#8CC43C", code: "MN", alliance: undefined },
    "La Compagnie": { name: "La Compagnie", color: "#94C4E4", code: "B0", alliance: undefined },
    "DreamJet SAS": { name: "La Compagnie", color: "#94C4E4", code: "B0", alliance: undefined },
    LATAM: { name: "LATAM Airlines", color: "#2A0087", code: "LA", alliance: "Star Alliance" },
    "LATAM Airlines": { name: "LATAM Airlines", color: "#2A0087", code: "LA", alliance: "Star Alliance" },
    "Lion Air": { name: "Lion", color: "#fb0102", code: "JT", alliance: undefined },
    "Lion Airlines": { name: "Lion", color: "#fb0102", code: "JT", alliance: undefined },
    LOT: { name: "LOT Polish", color: "#1A3171", code: "LO", alliance: "Star Alliance" },
    "LOT Airlines": { name: "LOT Polish", color: "#1A3171", code: "LO", alliance: "Star Alliance" },
    "LOT Polish": { name: "LOT Polish", color: "#1A3171", code: "LO", alliance: "Star Alliance" },
    "LOT Polish Airlines": { name: "LOT Polish", color: "#1A3171", code: "LO", alliance: "Star Alliance" },
    "Lot Airlines": { name: "LOT Polish", color: "#1A3171", code: "LO", alliance: "Star Alliance" },
    "Lot Polish": { name: "LOT Polish", color: "#1A3171", code: "LO", alliance: "Star Alliance" },
    "Lot Polish Airlines": { name: "LOT Polish", color: "#1A3171", code: "LO", alliance: "Star Alliance" },
    Lufthansa: { name: "Lufthansa", color: "#0A1D3D", code: "LH", alliance: "Star Alliance" },
    Luxair: { name: "Luxair", color: "#04ACBC", code: "LG", alliance: undefined },
    Malaysia: { name: "Malaysia", color: "#ED1C23", code: "MH", alliance: "Oneworld" },
    "Malaysia Airlines": { name: "Malaysia", color: "#ED1C23", code: "MH", alliance: "Oneworld" },
    Mango: { name: "Mango", color: "#EC7C1B", code: "JE", alliance: undefined },
    "Mango Airlines": { name: "Mango", color: "#EC7C1B", code: "JE", alliance: undefined },
    "Middle East": { name: "Middle East Airlines", color: "#047C5C", code: "ME", alliance: "SkyTeam" },
    "Middle East Airlines": { name: "Middle East Airlines", color: "#047C5C", code: "ME", alliance: "SkyTeam" },
    "Nok Air": { name: "Nok Air", code: "DD", color: "#FBCC0C", alliance: "Value Alliance" },
    "NOK Air": { name: "Nok Air", code: "DD", color: "#FBCC0C", alliance: "Value Alliance" },
    Nordwind: { name: "Nordwind", code: "N4", color: "#CC1C2C", alliance: undefined },
    "Nordwind Airlines": { name: "Nordwind", code: "N4", color: "#CC1C2C", alliance: undefined },
    Norwegian: { name: "Norwegian", code: "DY", color: "#043C54", alliance: undefined },
    "Norwegian Air": { name: "Norwegian", code: "DY", color: "#043C54", alliance: undefined },
    "Norwegian International": { name: "Norwegian", code: "DY", color: "#043C54", alliance: undefined },
    "Norwegian Air International": { name: "Norwegian", code: "DY", color: "#043C54", alliance: undefined },
    "Norwegian Air International Ltd": { name: "Norwegian", code: "DY", color: "#043C54", alliance: undefined },
    "Norwegian Air Shuttle": { name: "Norwegian", code: "DY", color: "#043C54", alliance: undefined },
    "Norwegian Air Sweden": { name: "Norwegian", code: "DY", color: "#043C54", alliance: undefined },
    "Norwegian Air UK": { name: "Norwegian", code: "DY", color: "#043C54", alliance: undefined },
    Oman: { name: "Oman Air", code: "WY", color: "#B49B5C", alliance: undefined },
    "Oman Air": { name: "Oman Air", code: "WY", color: "#B49B5C", alliance: undefined },
    PIA: { name: "PIA", code: "PK", color: "#AC9414", alliance: undefined },
    "Pakistan International Airlines": { name: "PIA", code: "PK", color: "#AC9414", alliance: undefined },
    "PIA Pakistan International Airlines": { name: "PIA", code: "PK", color: "#AC9414", alliance: undefined },
    Peach: { name: "Peach", code: "MM", color: "#D35C9C", alliance: undefined },
    "Peach Aviation": { name: "Peach", code: "MM", color: "#D35C9C", alliance: undefined },
    Pegasus: { name: "Pegasus", code: "PC", color: "#FBA404", alliance: undefined },
    "Pegasus Airlines": { name: "Pegasus", code: "PC", color: "#FBA404", alliance: undefined },
    Philippine: { name: "Philippine", code: "PR", color: "#F8C904", alliance: undefined },
    "Philippine Airlines": { name: "Philippine", code: "PR", color: "#F8C904", alliance: undefined },
    PAL: { name: "Philippine", code: "PR", color: "#F8C904", alliance: undefined },
    "Porter Airlines": { name: "Porter", color: "#0F2B53", code: "PD", alliance: undefined },
    Qantas: { name: "Qantas", color: "#E34538", code: "QF", alliance: "Oneworld" },
    "Qantas Airways": { name: "Qantas", color: "#E34538", code: "QF", alliance: undefined },
    Qatar: { name: "Qatar Airways", color: "#5C0632", code: "QR", alliance: "Oneworld" },
    "Qatar Airways": { name: "Qatar Airways", color: "#5C0632", code: "QR", alliance: "Oneworld" },
    Rex: { name: "Rex", code: "ZL", color: "#042C64", alliance: undefined },
    "Rex Airlines": { name: "Rex", code: "ZL", color: "#042C64", alliance: undefined },
    "Regional Express": { name: "Rex", code: "ZL", color: "#042C64", alliance: undefined },
    "Regional Express Airlines": { name: "Rex", code: "ZL", color: "#042C64", alliance: undefined },
    Rossiya: { name: "Rossiya", code: "FV", color: "#DC042C", alliance: undefined },
    "Rossiya Airlines": { name: "Rossiya", code: "FV", color: "#DC042C", alliance: undefined },
    RAM: { name: "Royal Air Maroc", code: "AT", color: "#c20831", alliance: "Oneworld" },
    "Royal Air Maroc": { name: "Royal Air Maroc", code: "AT", color: "#c20831", alliance: "Oneworld" },
    "Royal Brunei": { name: "Royal Brunei", code: "BI", color: "#FBEB04", alliance: undefined },
    "Royal Jordanian": { name: "Royal Jordanian", code: "RJ", color: "#A8854A", alliance: "Oneworld" },
    RwandAir: { name: "RwandAir", code: "WB", color: "#04549B", alliance: undefined },
    Rwandair: { name: "RwandAir", code: "WB", color: "#04549B", alliance: undefined },
    "Rwandair Express": { name: "RwandAir", code: "WB", color: "#04549B", alliance: undefined },
    Ryanair: { name: "Ryanair", color: "#f1c933", code: "FR", alliance: undefined },
    "Ryanair Ltd.": { name: "Ryanair", color: "#f1c933", code: "FR", alliance: undefined },
    RyanAir: { name: "Ryanair", color: "#f1c933", code: "FR", alliance: undefined },
    S7: { name: "S7", code: "S7", color: "#BED603", alliance: "Oneworld" },
    "S7 Airlines": { name: "S7", code: "S7", color: "#BED603", alliance: "Oneworld" },
    "Siberia Airlines": { name: "S7", code: "S7", color: "#BED603", alliance: "Oneworld" },
    Safair: { name: "Safair", code: "FA", color: "#DC0482", alliance: undefined },
    "Safair Ltd": { name: "Safair", code: "FA", color: "#DC0482", alliance: undefined },
    FlySafair: { name: "Safair", code: "FA", color: "#DC0482", alliance: undefined },
    Flysafair: { name: "Safair", code: "FA", color: "#DC0482", alliance: undefined },
    Saudia: { name: "Saudia", code: "SV", color: "#26265D", alliance: "SkyTeam" },
    "Saudi Arabian Airlines": { name: "Saudia", code: "SV", color: "#26265D", alliance: "SkyTeam" },
    SAS: { name: "Scandinavian", color: "#2B3087", code: "SK", alliance: "Star Alliance" },
    Scandinavian: { name: "Scandinavian", color: "#2B3087", code: "SK", alliance: "Star Alliance" },
    "Scandinavian Airlines": { name: "Scandinavian", color: "#2B3087", code: "SK", alliance: "Star Alliance" },
    Scoot: { name: "Scoot", color: "#FFE902", code: "TR", alliance: "Value Alliance" },
    "Scoot Airlines": { name: "Scoot", color: "#FFE902", code: "TR", alliance: "Value Alliance" },
    Shanghai: { name: "Shanghai", color: "#DC043B", code: "FM", alliance: "SkyTeam" },
    "Shanghai Airlines": { name: "Shanghai", color: "#DC043B", code: "FM", alliance: "SkyTeam" },
    Shenzen: { name: "Shenzen", color: "#CC0327", code: "ZH", alliance: "Star Alliance" },
    "Shenzen Airlines": { name: "Shenzen", color: "#CC0327", code: "ZH", alliance: "Star Alliance" },
    Singapore: { name: "Singapore", color: "#EFA952", code: "SQ", alliance: "Star Alliance" },
    "Singapore Airlines": { name: "Singapore", color: "#EFA952", code: "SQ", alliance: "Star Alliance" },
    Silver: { name: "Silver", color: "#f9ddd9", code: "3M", alliance: undefined },
    "Silver Airways": { name: "Silver", color: "#f9ddd9", code: "3M", alliance: undefined },
    "South African": { name: "South African", color: "#9D1E1E", code: "SA", alliance: "Star Alliance" },
    "South African Airways": { name: "South African", color: "#9D1E1E", code: "SA", alliance: "Star Alliance" },
    Southwest: { name: "WN", color: "#F6C04D", code: "WN", alliance: undefined },
    "Southwest Airlines": { name: "WN", color: "#F6C04D", code: "WN", alliance: undefined },
    WN: { name: "WN", color: "#F6C04D", code: "WN", alliance: undefined },
    SpiceJet: { name: "SpiceJet", code: "SG", color: "#9a544c", alliance: undefined },
    Spicejet: { name: "SpiceJet", code: "SG", color: "#9a544c", alliance: undefined },
    Spirit: { name: "Spirit", color: "#BBB140", code: "NK", alliance: undefined },
    "Spirit Airlines": { name: "Spirit", color: "#BBB140", code: "NK", alliance: undefined },
    Spring: { name: "Spring Airlines", color: "#048C54", code: "9C", alliance: undefined },
    "Spring Airlines": { name: "Spring Airlines", color: "#048C54", code: "9C", alliance: undefined },
    "Spring Airlines Japan": { name: "Spring Airlines", color: "#048C54", code: "9C", alliance: undefined },
    "SriLankan Airlines": { name: "SriLankan Airlines", color: "#01742F", code: "UL", alliance: "Oneworld" },
    "Sri Lankan Airlines": { name: "SriLankan Airlines", color: "#01742F", code: "UL", alliance: "Oneworld" },
    "Srilankan Airlines": { name: "SriLankan Airlines", color: "#01742F", code: "UL", alliance: "Oneworld" },
    Srilankan: { name: "SriLankan Airlines", color: "#01742F", code: "UL", alliance: "Oneworld" },
    SriLankan: { name: "SriLankan Airlines", color: "#01742F", code: "UL", alliance: "Oneworld" },
    "Sun Country": { name: "Sun Country", color: "#D79A71", code: "SY", alliance: undefined },
    "Sun Country Airlines": { name: "Sun Country", color: "#D79A71", code: "SY", alliance: undefined },
    Sunwing: { name: "Sunwing", color: "#F46C24", code: "WG", alliance: undefined },
    "Sunwing Airlines": { name: "Sunwing", color: "#F46C24", code: "WG", alliance: undefined },
    Swiss: { name: "Swiss", color: "#D42D21", code: "LX", alliance: "Star Alliance" },
    "Swiss International Air Lines": { name: "Swiss", color: "#D42D21", code: "LX", alliance: "Star Alliance" },
    SWISS: { name: "Swiss", color: "#D42D21", code: "LX", alliance: "Star Alliance" },
    Swoop: { name: "Swoop", color: "#E41C94", code: "WO", alliance: undefined },
    TAAG: { name: "TAAG", color: "#EB3424", code: "DT", alliance: undefined },
    "TAAG Angola": { name: "TAAG", color: "#EB3424", code: "DT", alliance: undefined },
    TAP: { name: "TAP", color: "#CC2C34", code: "TP", alliance: "Star Alliance" },
    "TAP Air": { name: "TAP", color: "#CC2C34", code: "TP", alliance: "Star Alliance" },
    "TAP Air Portugal": { name: "TAP", color: "#CC2C34", code: "TP", alliance: "Star Alliance" },
    "TAP Portugal": { name: "TAP", color: "#CC2C34", code: "TP", alliance: "Star Alliance" },
    Tarom: { name: "TAROM", color: "#041B5B", code: "RO", alliance: "SkyTeam" },
    TAROM: { name: "TAROM", color: "#041B5B", code: "RO", alliance: "SkyTeam" },
    Thai: { name: "Thai Airways", color: "#370E62", code: "TG", alliance: "Star Alliance" },
    "Thai Airways": { name: "Thai Airways", color: "#370E62", code: "TG", alliance: "Star Alliance" },
    Transavia: { name: "Transavia", color: "#0CAC5C", code: "HV", alliance: undefined },
    "Transavia Airlines": { name: "Transavia", color: "#0CAC5C", code: "HV", alliance: undefined },
    TUI: { name: "TUI", color: "#EC0404", code: "BY", alliance: undefined },
    "TUI Airways": { name: "TUI", color: "#EC0404", code: "BY", alliance: undefined },
    Tunisair: { name: "Tunisair", color: "#D40404", code: "TU", alliance: undefined },
    TunisAir: { name: "Tunisair", color: "#D40404", code: "TU", alliance: undefined },
    TUNISAIR: { name: "Tunisair", color: "#D40404", code: "TU", alliance: undefined },
    Turkish: { name: "Turkish", color: "#DB3832", code: "TK", alliance: "Star Alliance" },
    "Turkish Airlines": { name: "Turkish", color: "#DB3832", code: "TK", alliance: "Star Alliance" },
    UIA: { name: "UIA", color: "#1C3C74", code: "PS", alliance: undefined },
    Ukraine: { name: "UIA", color: "#1C3C74", code: "PS", alliance: undefined },
    "Ukraine International": { name: "UIA", color: "#1C3C74", code: "PS", alliance: undefined },
    "Ukraine International Airlines": { name: "UIA", color: "#1C3C74", code: "PS", alliance: undefined },
    "Ukraine Airlines": { name: "UIA", color: "#1C3C74", code: "PS", alliance: undefined },
    United: { name: "United", color: "#235EA6", code: "UA", alliance: "Star Alliance" },
    "United Airlines": { name: "United", color: "#235EA6", code: "UA", alliance: "Star Alliance" },
    Ural: { name: "Ural", color: "#E41C34", code: "U6", alliance: undefined },
    "Ural Airlines": { name: "Ural", color: "#E41C34", code: "U6", alliance: undefined },
    Utair: { name: "Utair", color: "#C9CFE2", code: "UT", alliance: undefined },
    Uzbekistan: { name: "Uzbekistan", color: "#FCD444", code: "HY", alliance: undefined },
    "Uzbekistan airways": { name: "Uzbekistan", color: "#FCD444", code: "HY", alliance: undefined },
    "Uzbekistan Airways": { name: "Uzbekistan", color: "#FCD444", code: "HY", alliance: undefined },
    Vietnam: { name: "Vietnam", color: "#046C84", code: "VN", alliance: "SkyTeam" },
    "Vietnam Airlines": { name: "Vietnam", color: "#046C84", code: "VN", alliance: "SkyTeam" },
    "Virgin Atlantic": { name: "Virgin Atlantic", color: "#AA1C2A", code: "VS", alliance: undefined },
    "Virgin Atlantic Airways": { name: "Virgin Atlantic", color: "#AA1C2A", code: "VS", alliance: undefined },
    "Virgin Australia": { name: "Virgin Australia", color: "#D41D3B", code: "VA", alliance: undefined },
    "Virgin Australia Airways": { name: "Virgin Australia", color: "#D41D3B", code: "VA", alliance: undefined },
    "Virgin Australia Airlines": { name: "Virgin Australia", color: "#D41D3B", code: "VA", alliance: undefined },
    Vistara: { name: "Vistara", color: "#47143D", code: "UK", alliance: undefined },
    "Viva Aerobus": { name: "Viva Aerobus", color: "#3CAC4C", code: "VB", alliance: undefined },
    Volaris: { name: "Volaris", code: "Y4", color: "#932493", alliance: undefined },
    Volotea: { name: "Volotea", code: "V7", color: "#E40C4C", alliance: undefined },
    "Volotea Airlines": { name: "Volotea", code: "V7", color: "#E40C4C", alliance: undefined },
    Vueling: { name: "Vueling", code: "VY", color: "#FBE364", alliance: undefined },
    "Vueling Airlines": { name: "Vueling", code: "VY", color: "#FBE364", alliance: undefined },
    WestJet: { name: "WestJet", color: "#4BA89C", code: "WS", alliance: undefined },
    "Wideroes Flyveselskap": { name: "Widerøe", code: "WF", color: "#4ea322", alliance: undefined },
    "Wizz Air": { name: "Wizz Air", color: "#C02B86", code: "W6", alliance: undefined },
    Xiamen: { name: "Xiamen", color: "#048CC4", code: "MF", alliance: "SkyTeam" },
    "Xiamen Airlines": { name: "Xiamen", color: "#048CC4", code: "MF", alliance: "SkyTeam" },
  },
  getAirlineName: function (airlineName) {
    if (!airlineName || typeof airlineName !== "string") {
      return;
    }
    let formattedAirlineName = airlineName.trim().replace(/\s+/g, " ");
    formattedAirlineName = cleanAlaskaAirlinesOperatingName(formattedAirlineName);
    const airlineDetails = this.airlineDetailsMap[formattedAirlineName];
    if (airlineDetails) {
      formattedAirlineName = airlineDetails.name;
    }

    return formattedAirlineName;
  },
  getAirlineDetails: function (airlineName) {
    let formattedAirlineName = airlineName.trim().replace(/\s+/g, " ");
    formattedAirlineName = cleanAlaskaAirlinesOperatingName(formattedAirlineName);
    return (
      this.airlineDetailsMap[formattedAirlineName] || {
        name: formattedAirlineName,
        color: "#DFCCFB",
      }
    );
  },
};
export default AirlineMap;
