import capitalize from "lodash.capitalize";

const cleanAlaskaAirlinesOperatingName = (airlineName) => {
  const alaskaRegex = /^(?<airline>[\s\w]*)\s+as\s+(?<dbaPart1>alaska)(?<dbaPart2>[a-z]{1,20})$/i;
  let cleanedName = airlineName;
  if (alaskaRegex.test(cleanedName)) {
    const nameGroups = cleanedName.match(alaskaRegex);
    cleanedName = `${nameGroups.groups.airline} as ${nameGroups.groups.dbaPart1} ${capitalize(
      nameGroups.groups.dbaPart2,
    )}`;
  }
  return cleanedName;
};

const AirlineMap = {
  airlineDetailsMap: {
    ANA: { display: "ANA", color: "#254897", code: "NH" },
    "ANA (All Nippon Airways)": { display: "ANA", color: "#0f4a8d" },
    "ANA Airlines": { display: "ANA", color: "#254897", code: "NH" },
    "All Nippon Airways": { display: "ANA", color: "#254897", code: "NH" },
    Aegean: { display: "Aegean", color: "#94A4D4", code: "A3" },
    "Aegean Airlines": { display: "Aegean", color: "#94A4D4", code: "A3" },
    "Aer Lingus": { display: "Aer Lingus", color: "#008274", code: "EI" },
    Aeroflot: { display: "Aeroflot", color: "#3C72A8", code: "SU" },
    "Aeroflot-Russian Airlines": { display: "Aeroflot", color: "#3C72A8", code: "SU" },
    Aerolineas: { display: "Aerolineas", color: "#007ac2", code: "AR" },
    "Aerolineas Argentinas": { display: "Aerolineas", color: "#007ac2", code: "AR" },
    Aeromexico: { display: "Aeromexico", color: "#000000", code: "AM" },
    AirAsia: { display: "AirAsia", color: "#E32526", code: "AK" },
    "Air Asia": { display: "AirAsia", color: "#E32526", code: "AK" },
    AIRASIA: { display: "AirAsia", color: "#E32526", code: "AK" },
    Aircalin: { display: "Aircalin", color: "#F44B24", code: "SB" },
    "Air Arabia": { display: "Air Arabia", color: "#FC0444", code: "G9" },
    "Air Astana": { display: "Air Astana", color: "#A48C64", code: "KC" },
    "Air Austral": { display: "Air Austral", color: "#26b5e3", code: "UU" },
    "Air Baltic": { display: "airBaltic", color: "#D3EB3B", code: "BT" },
    AirBaltic: { display: "airBaltic", color: "#D3EB3B", code: "BT" },
    airBaltic: { display: "airBaltic", color: "#D3EB3B", code: "BT" },
    "Air Belgium": { display: "Air Belgium", color: "#F43444", code: "KF" },
    "Air Canada": { display: "Air Canada", color: "#E53222", code: "AC" },
    "Air Caraibes": { display: "Air Caraibes", color: "#75C141", code: "TX" },
    "Air China": { display: "Air China", color: "#DF524B", code: "CA" },
    "Air Corsica": { display: "Air Corsica", color: "#048CCC", code: "XK" },
    "Air Dolomiti": { display: "Air Dolomiti", color: "#008e8f", code: "EN" },
    "Air Europa": { display: "Air Europa", color: "#0474CC", code: "UX" },
    "Air France": { display: "Air France", color: "#DB3832", code: "AF" },
    "Air India": { display: "Air India", color: "#D47346", code: "AI" },
    "Air India Limited": { display: "Air India", color: "#D47346", code: "AI" },
    "Air Macau": { display: "Air Macau", color: "#342464", code: "NX" },
    "Air Malta": { display: "Air Malta", color: "#e77027", code: "KM" },
    "Air Mauritius": { display: "Air Mauritius", color: "#C4042C", code: "MK" },
    "Air Namibia": { display: "Air Namibia", color: "#FBF304", code: "SW" },
    "Air New Zealand": { display: "Air New Zealand", color: "#241C24", code: "NZ" },
    "Air North": { display: "Air North", color: "#F47B20", code: "4N" },
    "Air Seoul": { display: "Air Seoul", color: "#048B7B", code: "RS" },
    "Air Serbia": { display: "Air Serbia", color: "#0C4484", code: "JU" },
    "Air Tahiti Nui": { display: "Air Tahiti Nui", color: "#2CCCD4", code: "TN" },
    "Air Transat": { display: "Air Transat", color: "#3CBCEC", code: "TS" },
    "Air Vanuatu": { display: "Air Vanuatu", color: "#009543", code: "NF" },
    "Air Vistara": { display: "Vistara", color: "#47143D", code: "UK" },
    Alaska: { display: "Alaska", color: "#51172C", code: "AS" },
    "Alaska Airlines": { display: "Alaska", color: "#51172C", code: "AS" },
    Alitilia: { display: "ITA Airways", color: "#04643C", code: "AZ" },
    "ITA Airways": { display: "ITA Airways", color: "#04643C", code: "AZ" },
    Allegiant: { display: "Allegiant", color: "#FBCE21", code: "G4" },
    "Allegiant Air": { display: "Allegiant", color: "#FBCE21", code: "G4" },
    American: { display: "American", color: "#C5423E", code: "AA" },
    "American Airlines": { display: "American", color: "#C5423E", code: "AA" },
    Austrian: { display: "Austrian", color: "#D41C04", code: "OS" },
    "Austrian Airlines": { display: "Austrian", color: "#D41C04", code: "OS" },
    Asiana: { display: "Asiana", color: "#FC0404", code: "OZ" },
    "Asiana Air": { display: "Asiana", color: "#FC0404", code: "OZ" },
    "Asiana Airlines": { display: "Asiana", color: "#FC0404", code: "OZ" },
    Avianca: { display: "Avianca", color: "#DA291C", code: "AV" },
    Azerbaijan: { display: "Azerbaijan", color: "#7CCCE4", code: "J2" },
    "Azerbaijan Airlines": { display: "Azerbaijan", color: "#7CCCE4", code: "J2" },
    Azul: { display: "Azul Brazilian", color: "#6ca9db", code: "AD" },
    "Azul Linhas Aereas Brasileiras": { display: "Azul Brazilian", color: "#6ca9db", code: "AD" },
    "Breeze Airways": { display: "Breeze Airways", color: "#ABC3EB", code: "MX" },
    British: { display: "British", color: "#EA8E8C", code: "BA" },
    "British Airways": { display: "British", color: "#EA8E8C", code: "BA" },
    "Cathay Dragon": { display: "Cathay", color: "#2A645A", code: "CX" },
    "Cathay Pacific": { display: "Cathay", color: "#2A645A", code: "CX" },
    "China Airlines": { display: "China Airlines", color: "#DAABB1", code: "CI" },
    "China Eastern Airlines": { display: "China Eastern", color: "#A9545F", code: "MU" },
    "China Southern Airlines": { display: "China Southern", color: "#93ACCA", code: "CZ" },
    "Copa Airlines": { display: "Copa", color: "#0060a9", code: "CM" },
    Delta: { display: "Delta", color: "#EE722E", code: "DL" },
    "Delta Air Lines": { display: "Delta", color: "#EE722E", code: "DL" },
    EGYPTAIR: { display: "Egyptair", color: "#00265d", code: "MS" },
    "EVA Airways": { display: "EVA", color: "#6F9F64", code: "BR" },
    easyJet: { display: "easyJet", color: "#ff6600", code: "EC" },
    EasyJet: { display: "easyJet", color: "#ff6600", code: "EC" },
    Easyjet: { display: "easyJet", color: "#ff6600", code: "EC" },
    EgyptAir: { display: "Egyptair", color: "#00265d", code: "MS" },
    Egyptair: { display: "Egyptair", color: "#00265d", code: "MS" },
    Emirates: { display: "Emirates", color: "#D71A21", code: "EK" },
    "Emirates Airlines": { display: "Emirates", color: "#CF534F", code: "EK" },
    "Etihad Airways": { display: "Etihad Airways", color: "#251019", code: "EY" },
    Finnair: { display: "Finnair", color: "#7F1F89", code: "AY" },
    Frontier: { display: "Frontier", color: "#378055", code: "F9" },
    "Frontier Airlines": { display: "Frontier", color: "#378055", code: "F9" },
    "Hawaiian Airlines": { display: "Hawaiian", color: "#4D388A", code: "HA" },
    Iberia: { display: "Iberia", color: "#D05653", code: "IB" },
    "Iberia Airlines": { display: "Iberia", color: "#D05653", code: "IB" },
    Icelandair: { display: "Icelandair", color: "#043C84", code: "FI" },
    IndiGo: { display: "IndiGo", color: "#3A469D", code: "6E" },
    "IndiGo Airlines": { display: "IndiGo", color: "#3A469D", code: "6E" },
    Indigo: { display: "IndiGo", color: "#3A469D", code: "6E" },
    Interjet: { display: "Interjet", color: "#A8A8A8", code: "4O" },
    "Japan Airlines": { display: "Japan Airlines", color: "#E56E69", code: "JL" },
    "Jazeera Airways": { display: "Jazeera Airways", color: "#1484C4", code: "J9" },
    jetBlue: { display: "jetBlue", color: "#5F90C8", code: "B6" },
    JetBlue: { display: "jetBlue", color: "#5F90C8", code: "B6" },
    "JetBlue Airways": { display: "jetBlue", color: "#5F90C8", code: "B6" },
    Jetblue: { display: "jetBlue", color: "#5F90C8", code: "B6" },
    "Jetblue Airways": { display: "jetBlue", color: "#5F90C8", code: "B6" },
    KLM: { display: "KLM", color: "#44A0DC", code: "KL" },
    "KLM Royal Dutch Airlines": { display: "KLM", color: "#44A0DC", code: "KL" },
    "KLM-Royal Dutch Airlines": { display: "KLM", color: "#44A0DC", code: "KL" },
    "Korean Air": { display: "Korean Air", color: "#154D9E", code: "KE" },
    "LATAM Airlines": { display: "LATAM Airlines", color: "#2A0087", code: "LA" },
    LOT: { display: "LOT Polish", color: "#1A3171", code: "LO" },
    "LOT Airlines": { display: "LOT Polish", color: "#1A3171", code: "LO" },
    "LOT Polish": { display: "LOT Polish", color: "#1A3171", code: "LO" },
    "LOT Polish Airlines": { display: "LOT Polish", color: "#1A3171", code: "LO" },
    "Lot Airlines": { display: "LOT Polish", color: "#1A3171", code: "LO" },
    "Lot Polish": { display: "LOT Polish", color: "#1A3171", code: "LO" },
    "Lot Polish Airlines": { display: "LOT Polish", color: "#1A3171", code: "LO" },
    Lufthansa: { display: "Lufthansa", color: "#0A1D3D", code: "LH" },
    Malaysia: { display: "Malaysia", color: "#ED1C23", code: "MH" },
    "Malaysia Airlines": { display: "Malaysia", color: "#ED1C23", code: "MH" },
    "Porter Airlines": { display: "Porter", color: "#0F2B53", code: "PD" },
    "Qantas Airways": { display: "Qantas", color: "#E34538", code: "QF" },
    "Qatar Airways": { display: "Qatar Airways", color: "#5C0632", code: "QR" },
    Ryanair: { display: "Ryanair", color: "#f1c933", code: "FR" },
    SAS: { display: "Scandinavian", color: "#2B3087", code: "SK" },
    SWISS: { display: "Swiss", color: "#D42D21", code: "LX" },
    "Scandinavian Airlines": { display: "Scandinavian", color: "#2B3087", code: "SK" },
    "Singapore Airlines": { display: "Singapore", color: "#EFA952", code: "SQ" },
    Southwest: { display: "WN", color: "#F6C04D", code: "WN" },
    "Southwest Airlines": { display: "WN", color: "#F6C04D", code: "WN" },
    Spirit: { display: "Spirit", color: "#BBB140", code: "NK" },
    "Spirit Airlines": { display: "Spirit", color: "#BBB140", code: "NK" },
    "Sun Country": { display: "Sun Country", color: "#D79A71", code: "SY" },
    "Sun Country Airlines": { display: "Sun Country", color: "#D79A71", code: "SY" },
    Swiss: { display: "Swiss", color: "#D42D21", code: "LX" },
    "Swiss International Air Lines": { display: "Swiss", color: "#D42D21", code: "LX" },
    TAP: { display: "TAP", color: "#CC2C34", code: "TP" },
    "TAP Air Portugal": { display: "TAP", color: "#CC2C34", code: "TP" },
    Turkish: { display: "Turkish", color: "#DB3832", code: "TK" },
    "Turkish Airlines": { display: "Turkish", color: "#DB3832", code: "TK" },
    United: { display: "United", color: "#235EA6", code: "UA" },
    "United Airlines": { display: "United", color: "#235EA6", code: "UA" },
    "Virgin Atlantic": { display: "Virgin Atlantic", color: "#AA1C2A", code: "VS" },
    "Virgin Atlantic Airways": { display: "Virgin Atlantic", color: "#AA1C2A", code: "VS" },
    Vistara: { display: "Vistara", color: "#47143D", code: "UK" },
    WN: { display: "WN", color: "#F6C04D", code: "WN" },
    WestJet: { display: "WestJet", color: "#4BA89C", code: "WS" },
  },
  getAirlineName: function (airlineName) {
    if (!airlineName || typeof airlineName !== "string") {
      return;
    }
    let formattedAirlineName = airlineName.trim().replace(/\s+/g, " ");
    formattedAirlineName = cleanAlaskaAirlinesOperatingName(formattedAirlineName);
    const airlineDetails = this.airlineDetailsMap[formattedAirlineName];
    if (airlineDetails) {
      formattedAirlineName = airlineDetails.display;
    }

    return formattedAirlineName;
  },
  getAirlineDetails: function (airlineName) {
    let formattedAirlineName = airlineName.trim().replace(/\s+/g, " ");
    formattedAirlineName = cleanAlaskaAirlinesOperatingName(formattedAirlineName);
    return (
      this.airlineDetailsMap[formattedAirlineName] || {
        display: formattedAirlineName,
        color: "#DFCCFB",
      }
    );
  },
};
export default AirlineMap;
