module.exports = {
  manifest_version: 2,
  name: "FlightPenguin",
  short_name: "FlightPenguin",
  description:
    "Take the pain out of flight search with Flight Penguin - a browser extension from some of Hipmunk's founders, employees, and fans.",
  version: "1.20.0",
  content_security_policy:
    "script-src 'self' https://www.google-analytics.com https://apis.google.com; object-src 'self'",
  web_accessible_resources: [
    "index.html",
    "images/*.svg",
    "images/*.png",
    "images/*.webp",
    "icons/*.png",
    "icons/*.svg",
  ],
  icons: {
    "16": "icons/icon.png",
    "48": "icons/icon.png",
    "128": "icons/icon128.png",
  },
  browser_action: {
    default_title: "FlightPenguin",
  },
  permissions: [
    "tabs",
    "identity",
    "identity.email",
    "geolocation",
    "https://www.googleapis.com/",
    "https://subscribe.flightpenguin.com/",
  ],
  content_scripts: [
    {
      matches: ["https://www.trip.com/flights/*"],
      css: ["css/contentScript.css"],
      js: ["content_scripts/trip.js"],
    },
    {
      matches: ["https://www.cheapoair.com/air*"],
      css: ["css/contentScript.css"],
      js: ["content_scripts/cheapoair.js"],
    },
    {
      matches: ["https://www.kiwi.com/us/search/results/*"],
      css: ["css/contentScript.css"],
      js: ["content_scripts/kiwi.js"],
    },
    {
      matches: ["https://www.momondo.com/flight-search/*", "https://www.momondo.com/book/*"],
      css: ["css/contentScript.css"],
      js: ["content_scripts/momondo.js"],
    },
    {
      matches: ["https://flightpenguin.com/*"],
      exclude_matches: ["https://flightpenguin.com/talking_travel*"],
      js: ["content_scripts/flightpenguin.js"],
      run_at: "document_start",
    },
    {
      matches: [
        "*://*.aa.com/*",
        "*://*.aeromexico.com/*",
        "*://*.aircanada.com/*",
        "*://*.airchina.com/*",
        "*://*.alaskaairlines.com/*",
        "*://*.allegiantair.com/*",
        "*://*.ana.co.jp/*",
        "*://*.ba.com/*",
        "*://*.airfrance.com/*",
        "*://*.cheapoair.com/*",
        "*://*.csair.com/*",
        "*://*.ctrip.com/*",
        "*://*.delta.com/*",
        "*://*.easyjet.com/*",
        "*://*.emirates.com/*",
        "*://*.expedia.com/*",
        "*://*.flyfrontier.com/*",
        "*://*.goibibo.com/*",
        "*://*.hawaiianairlines.com/*",
        "*://*.hurb.com/*",
        "*://*.iberia.com/*",
        "*://*.jalan.net/*",
        "*://*.jetblue.com/*",
        "*://*.jsx.com/*",
        "*://*.kayak.com/*",
        "*://*.kiwi.com/*",
        "*://*.klm.com/*",
        "*://*.latamairlines.com/*",
        "*://*.lufthansa.com/*",
        "*://*.makemytrip.com/*",
        "*://*.momondo.com/*",
        "*://*.orbitz.com/*",
        "*://*.priceline.com/*",
        "*://*.ryanair.com/*",
        "*://*.skiplagged.com/*",
        "*://*.skyscanner.com/*",
        "*://*.spirit.com/*",
        "*://*.southwest.com/*",
        "*://*.suncountry.com/*",
        "*://*.travel.rakuten.co.jp/*",
        "*://*.trip.com/*",
        "*://*.tripadvisor.com/CheapFlightsHome*",
        "*://*.tripadvisor.co.uk/CheapFlightsHome*",
        "*://*.turkishairlines.com/*",
        "*://*.united.com/*",
        "*://*.vivaaerobus.com/*",
        "*://*.volaris.com/*",
        "*://*.westjet.com/*",
      ],
      exclude_matches: [
        "https://us.trip.com/flights/*",
        "https://www.trip.com/flights/*",
        "https://www.southwest.com/air/booking/select.html?*",
        "https://www.southwest.com/air/booking/index.html?*",
        "https://www.momondo.com/flight-search/*",
        "https://www.momondo.com/book/*",
        "https://www.kiwi.com/us/search/results/*",
        "https://www.cheapoair.com/air/*",
      ],
      js: ["content_scripts/generic.js"],
      run_at: "document_end",
    },
  ],
  background: {
    page: "background.html",
    persistent: false,
  },
};
