import { Box, Provider as BumbagProvider } from "bumbag";
import React from "react";
import ReactDom from "react-dom";

import { TimelineContainer } from "./components/TimelineContainer";

const root = document.getElementById("react-root");

if (root) {
  ReactDom.render(
    <BumbagProvider>
      <Box paddingTop="400px">
        <TimelineContainer
          flightType={"DEPARTURE"}
          itineraries={[
            {
              departureFlight: {
                marketingAirline: "United",
                operatingAirline: null,
                fromTime: "6:00am",
                toTime: "7:27am",
                duration: "1h 27m",
                layovers: [],
                fromTimeDetails: {
                  hours: 6,
                  displayHours: 6,
                  minutes: 0,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 7,
                  displayHours: 7,
                  minutes: 27,
                  timeOfDay: "am",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "United",
                  color: "#235EA6",
                  code: "UA",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$174",
            },
            {
              departureFlight: {
                marketingAirline: "Alaska",
                operatingAirline: "Skywest Airlines As Alaskaskywest",
                fromTime: "6:00am",
                toTime: "7:28am",
                duration: "1h 28m",
                layovers: [],
                fromTimeDetails: {
                  hours: 6,
                  displayHours: 6,
                  minutes: 0,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 7,
                  displayHours: 7,
                  minutes: 28,
                  timeOfDay: "am",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "Alaska",
                  color: "#51172C",
                  code: "AS",
                },
                operatingAirlineDetails: {
                  display: "Skywest Airlines As Alaskaskywest",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$174",
            },
            {
              departureFlight: {
                marketingAirline: "jetBlue",
                operatingAirline: null,
                fromTime: "6:55am",
                toTime: "8:26am",
                duration: "1h 31m",
                layovers: [],
                fromTimeDetails: {
                  hours: 6,
                  displayHours: 6,
                  minutes: 55,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 8,
                  displayHours: 8,
                  minutes: 26,
                  timeOfDay: "am",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "jetBlue",
                  color: "#5F90C8",
                  code: "B6",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$174",
            },
            {
              departureFlight: {
                marketingAirline: "jetBlue",
                operatingAirline: null,
                fromTime: "8:09am",
                toTime: "9:44am",
                duration: "1h 35m",
                layovers: [],
                fromTimeDetails: {
                  hours: 8,
                  displayHours: 8,
                  minutes: 9,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 9,
                  displayHours: 9,
                  minutes: 44,
                  timeOfDay: "am",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "jetBlue",
                  color: "#5F90C8",
                  code: "B6",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$174",
            },
            {
              departureFlight: {
                marketingAirline: "American",
                operatingAirline: "Skywest Airlines As American Eagle",
                fromTime: "6:25am",
                toTime: "11:13am",
                duration: "4h 48m",
                layovers: [
                  {
                    fromTime: "6:25am",
                    toTime: "8:37am",
                    from: "SFO",
                    to: "PHX",
                    operatingAirline: "American  Airlines",
                    duration: "2h 12m ",
                    fromTimeDetails: {
                      hours: 6,
                      displayHours: 6,
                      minutes: 25,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 8,
                      displayHours: 8,
                      minutes: 37,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                  {
                    fromTime: "9:30am",
                    toTime: "11:13am",
                    from: "PHX",
                    to: "LAX",
                    operatingAirline: "American  Airlines       operated  by  Skywest  Airlines  As  American  Eagle",
                    duration: "1h 43m ",
                    fromTimeDetails: {
                      hours: 9,
                      displayHours: 9,
                      minutes: 30,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 11,
                      displayHours: 11,
                      minutes: 13,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                ],
                fromTimeDetails: {
                  hours: 6,
                  displayHours: 6,
                  minutes: 25,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 11,
                  displayHours: 11,
                  minutes: 13,
                  timeOfDay: "am",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "American",
                  color: "#C5423E",
                  code: "AA",
                },
                operatingAirlineDetails: {
                  display: "Skywest Airlines As American Eagle",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$183",
            },
            {
              departureFlight: {
                marketingAirline: "American",
                operatingAirline: null,
                fromTime: "6:25am",
                toTime: "12:18pm",
                duration: "5h 53m",
                layovers: [
                  {
                    fromTime: "6:25am",
                    toTime: "8:37am",
                    from: "SFO",
                    to: "PHX",
                    operatingAirline: "American  Airlines",
                    duration: "2h 12m ",
                    fromTimeDetails: {
                      hours: 6,
                      displayHours: 6,
                      minutes: 25,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 8,
                      displayHours: 8,
                      minutes: 37,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                  {
                    fromTime: "10:51am",
                    toTime: "12:18pm",
                    from: "PHX",
                    to: "LAX",
                    operatingAirline: "American  Airlines",
                    duration: "1h 27m ",
                    fromTimeDetails: {
                      hours: 10,
                      displayHours: 10,
                      minutes: 51,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 12,
                      displayHours: 12,
                      minutes: 18,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                ],
                fromTimeDetails: {
                  hours: 6,
                  displayHours: 6,
                  minutes: 25,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 12,
                  displayHours: 12,
                  minutes: 18,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "American",
                  color: "#C5423E",
                  code: "AA",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$183",
            },
            {
              departureFlight: {
                marketingAirline: "American",
                operatingAirline: null,
                fromTime: "10:45am",
                toTime: "5:00pm",
                duration: "6h 15m",
                layovers: [
                  {
                    fromTime: "10:45am",
                    toTime: "12:49pm",
                    from: "SFO",
                    to: "PHX",
                    operatingAirline: "American  Airlines",
                    duration: "2h 4m ",
                    fromTimeDetails: {
                      hours: 10,
                      displayHours: 10,
                      minutes: 45,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 12,
                      displayHours: 12,
                      minutes: 49,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    fromTime: "3:32pm",
                    toTime: "5:00pm",
                    from: "PHX",
                    to: "LAX",
                    operatingAirline: "American  Airlines",
                    duration: "1h 28m ",
                    fromTimeDetails: {
                      hours: 15,
                      displayHours: 3,
                      minutes: 32,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 17,
                      displayHours: 5,
                      minutes: 0,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                ],
                fromTimeDetails: {
                  hours: 10,
                  displayHours: 10,
                  minutes: 45,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 17,
                  displayHours: 5,
                  minutes: 0,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "American",
                  color: "#C5423E",
                  code: "AA",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$183",
            },
            {
              departureFlight: {
                marketingAirline: "Frontier",
                operatingAirline: null,
                fromTime: "8:41am",
                toTime: "3:33pm",
                duration: "6h 52m",
                layovers: [
                  {
                    fromTime: "8:41am",
                    toTime: "10:44am",
                    from: "SFO",
                    to: "PHX",
                    operatingAirline: "Frontier  Airlines",
                    duration: "2h 3m ",
                    fromTimeDetails: {
                      hours: 8,
                      displayHours: 8,
                      minutes: 41,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 10,
                      displayHours: 10,
                      minutes: 44,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                  {
                    fromTime: "2:16pm",
                    toTime: "3:33pm",
                    from: "PHX",
                    to: "ONT",
                    operatingAirline: "Frontier  Airlines",
                    duration: "1h 17m ",
                    fromTimeDetails: {
                      hours: 14,
                      displayHours: 2,
                      minutes: 16,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 15,
                      displayHours: 3,
                      minutes: 33,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                ],
                fromTimeDetails: {
                  hours: 8,
                  displayHours: 8,
                  minutes: 41,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 15,
                  displayHours: 3,
                  minutes: 33,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "Frontier",
                  color: "#378055",
                  code: "F9",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$204",
            },
            {
              departureFlight: {
                marketingAirline: "United",
                operatingAirline: null,
                fromTime: "8:30am",
                toTime: "9:57am",
                duration: "1h 27m",
                layovers: [],
                fromTimeDetails: {
                  hours: 8,
                  displayHours: 8,
                  minutes: 30,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 9,
                  displayHours: 9,
                  minutes: 57,
                  timeOfDay: "am",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "United",
                  color: "#235EA6",
                  code: "UA",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$219",
            },
            {
              departureFlight: {
                marketingAirline: "Delta",
                operatingAirline: null,
                fromTime: "6:05am",
                toTime: "7:28am",
                duration: "1h 23m",
                layovers: [],
                fromTimeDetails: {
                  hours: 6,
                  displayHours: 6,
                  minutes: 5,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 7,
                  displayHours: 7,
                  minutes: 28,
                  timeOfDay: "am",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "Delta",
                  color: "#EE722E",
                  code: "DL",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$229",
            },
            {
              departureFlight: {
                marketingAirline: "Alaska",
                operatingAirline: "Horizon Air As Alaskahorizon",
                fromTime: "8:45am",
                toTime: "10:13am",
                duration: "1h 28m",
                layovers: [],
                fromTimeDetails: {
                  hours: 8,
                  displayHours: 8,
                  minutes: 45,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 10,
                  displayHours: 10,
                  minutes: 13,
                  timeOfDay: "am",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "Alaska",
                  color: "#51172C",
                  code: "AS",
                },
                operatingAirlineDetails: {
                  display: "Horizon Air As Alaskahorizon",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$229",
            },
            {
              departureFlight: {
                marketingAirline: "Delta",
                operatingAirline: "Skywest DBA Delta Connection",
                fromTime: "3:18pm",
                toTime: "5:00pm",
                duration: "1h 42m",
                layovers: [],
                fromTimeDetails: {
                  hours: 15,
                  displayHours: 3,
                  minutes: 18,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 17,
                  displayHours: 5,
                  minutes: 0,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "Delta",
                  color: "#EE722E",
                  code: "DL",
                },
                operatingAirlineDetails: {
                  display: "Skywest DBA Delta Connection",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$229",
            },
            {
              departureFlight: {
                marketingAirline: "American",
                operatingAirline: null,
                fromTime: "2:05pm",
                toTime: "6:25pm",
                duration: "4h 20m",
                layovers: [
                  {
                    fromTime: "2:05pm",
                    toTime: "4:16pm",
                    from: "SFO",
                    to: "PHX",
                    operatingAirline: "American  Airlines",
                    duration: "2h 11m ",
                    fromTimeDetails: {
                      hours: 14,
                      displayHours: 2,
                      minutes: 5,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 16,
                      displayHours: 4,
                      minutes: 16,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    fromTime: "4:55pm",
                    toTime: "6:25pm",
                    from: "PHX",
                    to: "LAX",
                    operatingAirline: "American  Airlines",
                    duration: "1h 30m ",
                    fromTimeDetails: {
                      hours: 16,
                      displayHours: 4,
                      minutes: 55,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 18,
                      displayHours: 6,
                      minutes: 25,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                ],
                fromTimeDetails: {
                  hours: 14,
                  displayHours: 2,
                  minutes: 5,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 18,
                  displayHours: 6,
                  minutes: 25,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "American",
                  color: "#C5423E",
                  code: "AA",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$239",
            },
            {
              departureFlight: {
                marketingAirline: "United",
                operatingAirline: null,
                fromTime: "10:30pm",
                toTime: "7:34am+1",
                duration: "9h 4m",
                layovers: [
                  {
                    fromTime: "10:30pm",
                    toTime: "12:01am+1",
                    from: "SFO",
                    to: "LAS",
                    operatingAirline: "United",
                    duration: "1h 31m ",
                    fromTimeDetails: {
                      hours: 22,
                      displayHours: 10,
                      minutes: 30,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 24,
                      displayHours: 12,
                      minutes: 1,
                      timeOfDay: "am",
                      excessDays: "+1",
                    },
                  },
                  {
                    fromTime: "6:27am",
                    toTime: "7:34am",
                    from: "LAS",
                    to: "LAX",
                    operatingAirline: "United",
                    duration: "1h 7m ",
                    fromTimeDetails: {
                      hours: 6,
                      displayHours: 6,
                      minutes: 27,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 7,
                      displayHours: 7,
                      minutes: 34,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                ],
                fromTimeDetails: {
                  hours: 22,
                  displayHours: 10,
                  minutes: 30,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 31,
                  displayHours: 7,
                  minutes: 34,
                  timeOfDay: "am",
                  excessDays: "+1",
                },
                marketingAirlineDetails: {
                  display: "United",
                  color: "#235EA6",
                  code: "UA",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$252",
            },
            {
              departureFlight: {
                marketingAirline: "jetBlue",
                operatingAirline: null,
                fromTime: "3:07pm",
                toTime: "4:42pm",
                duration: "1h 35m",
                layovers: [],
                fromTimeDetails: {
                  hours: 15,
                  displayHours: 3,
                  minutes: 7,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 16,
                  displayHours: 4,
                  minutes: 42,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "jetBlue",
                  color: "#5F90C8",
                  code: "B6",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$269",
            },
            {
              departureFlight: {
                marketingAirline: "United",
                operatingAirline: null,
                fromTime: "10:30pm",
                toTime: "11:57pm",
                duration: "1h 27m",
                layovers: [],
                fromTimeDetails: {
                  hours: 22,
                  displayHours: 10,
                  minutes: 30,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 23,
                  displayHours: 11,
                  minutes: 57,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "United",
                  color: "#235EA6",
                  code: "UA",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$278",
            },
            {
              departureFlight: {
                marketingAirline: "Frontier",
                operatingAirline: null,
                fromTime: "12:49am",
                toTime: "11:06am",
                duration: "10h 17m",
                layovers: [
                  {
                    fromTime: "12:49am",
                    toTime: "4:28am",
                    from: "SFO",
                    to: "DEN",
                    operatingAirline: "Frontier  Airlines",
                    duration: "2h 39m ",
                    fromTimeDetails: {
                      hours: 0,
                      displayHours: 12,
                      minutes: 49,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 4,
                      displayHours: 4,
                      minutes: 28,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                  {
                    fromTime: "9:45am",
                    toTime: "11:06am",
                    from: "DEN",
                    to: "ONT",
                    operatingAirline: "Frontier  Airlines",
                    duration: "2h 21m ",
                    fromTimeDetails: {
                      hours: 9,
                      displayHours: 9,
                      minutes: 45,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 11,
                      displayHours: 11,
                      minutes: 6,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                ],
                fromTimeDetails: {
                  hours: 0,
                  displayHours: 12,
                  minutes: 49,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 11,
                  displayHours: 11,
                  minutes: 6,
                  timeOfDay: "am",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "Frontier",
                  color: "#378055",
                  code: "F9",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$286",
            },
            {
              departureFlight: {
                marketingAirline: "United",
                operatingAirline: "Skywest DBA United Express",
                fromTime: "10:30pm",
                toTime: "7:26am+1",
                duration: "8h 56m",
                layovers: [
                  {
                    fromTime: "10:30pm",
                    toTime: "11:14pm",
                    from: "SFO",
                    to: "SMF",
                    operatingAirline: "United       operated  by  Skywest  DBA  United  Express",
                    duration: "44m ",
                    fromTimeDetails: {
                      hours: 22,
                      displayHours: 10,
                      minutes: 30,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 23,
                      displayHours: 11,
                      minutes: 14,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    fromTime: "6:00am+1",
                    toTime: "7:26am",
                    from: "SMF",
                    to: "LAX",
                    operatingAirline: "United       operated  by  Skywest  DBA  United  Express",
                    duration: "1h 26m ",
                    fromTimeDetails: {
                      hours: 30,
                      displayHours: 6,
                      minutes: 0,
                      timeOfDay: "am",
                      excessDays: "+1",
                    },
                    toTimeDetails: {
                      hours: 7,
                      displayHours: 7,
                      minutes: 26,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                ],
                fromTimeDetails: {
                  hours: 22,
                  displayHours: 10,
                  minutes: 30,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 31,
                  displayHours: 7,
                  minutes: 26,
                  timeOfDay: "am",
                  excessDays: "+1",
                },
                marketingAirlineDetails: {
                  display: "United",
                  color: "#235EA6",
                  code: "UA",
                },
                operatingAirlineDetails: {
                  display: "Skywest DBA United Express",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$300",
            },
            {
              departureFlight: {
                marketingAirline: "Delta",
                operatingAirline: "Skywest DBA Delta Connection",
                fromTime: "8:20pm",
                toTime: "9:55pm",
                duration: "1h 35m",
                layovers: [],
                fromTimeDetails: {
                  hours: 20,
                  displayHours: 8,
                  minutes: 20,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 21,
                  displayHours: 9,
                  minutes: 55,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "Delta",
                  color: "#EE722E",
                  code: "DL",
                },
                operatingAirlineDetails: {
                  display: "Skywest DBA Delta Connection",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$309",
            },
            {
              departureFlight: {
                marketingAirline: "United",
                operatingAirline: "Skywest DBA United Express",
                fromTime: "1:08pm",
                toTime: "5:42pm",
                duration: "4h 34m",
                layovers: [
                  {
                    fromTime: "1:08pm",
                    toTime: "4:01pm",
                    from: "SFO",
                    to: "SLC",
                    operatingAirline: "United       operated  by  Skywest  DBA  United  Express",
                    duration: "1h 53m ",
                    fromTimeDetails: {
                      hours: 13,
                      displayHours: 1,
                      minutes: 8,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 16,
                      displayHours: 4,
                      minutes: 1,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    fromTime: "4:45pm",
                    toTime: "5:42pm",
                    from: "SLC",
                    to: "LAX",
                    operatingAirline: "United       operated  by  Skywest  DBA  United  Express",
                    duration: "1h 57m ",
                    fromTimeDetails: {
                      hours: 16,
                      displayHours: 4,
                      minutes: 45,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 17,
                      displayHours: 5,
                      minutes: 42,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                ],
                fromTimeDetails: {
                  hours: 13,
                  displayHours: 1,
                  minutes: 8,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 17,
                  displayHours: 5,
                  minutes: 42,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "United",
                  color: "#235EA6",
                  code: "UA",
                },
                operatingAirlineDetails: {
                  display: "Skywest DBA United Express",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$330",
            },
            {
              departureFlight: {
                marketingAirline: "Delta",
                operatingAirline: "Skywest DBA Delta Connection",
                fromTime: "5:15pm",
                toTime: "6:54pm",
                duration: "1h 39m",
                layovers: [],
                fromTimeDetails: {
                  hours: 17,
                  displayHours: 5,
                  minutes: 15,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 18,
                  displayHours: 6,
                  minutes: 54,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "Delta",
                  color: "#EE722E",
                  code: "DL",
                },
                operatingAirlineDetails: {
                  display: "Skywest DBA Delta Connection",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$339",
            },
            {
              departureFlight: {
                marketingAirline: "Alaska",
                operatingAirline: null,
                fromTime: "7:45pm",
                toTime: "8:50am+1",
                duration: "13h 5m",
                layovers: [
                  {
                    fromTime: "7:45pm",
                    toTime: "10:00pm",
                    from: "SFO",
                    to: "SEA",
                    operatingAirline: "Alaska  Airlines",
                    duration: "2h 15m ",
                    fromTimeDetails: {
                      hours: 19,
                      displayHours: 7,
                      minutes: 45,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 22,
                      displayHours: 10,
                      minutes: 0,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    fromTime: "6:00am+1",
                    toTime: "8:50am",
                    from: "SEA",
                    to: "LAX",
                    operatingAirline: "Alaska  Airlines",
                    duration: "2h 50m ",
                    fromTimeDetails: {
                      hours: 30,
                      displayHours: 6,
                      minutes: 0,
                      timeOfDay: "am",
                      excessDays: "+1",
                    },
                    toTimeDetails: {
                      hours: 8,
                      displayHours: 8,
                      minutes: 50,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                ],
                fromTimeDetails: {
                  hours: 19,
                  displayHours: 7,
                  minutes: 45,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 32,
                  displayHours: 8,
                  minutes: 50,
                  timeOfDay: "am",
                  excessDays: "+1",
                },
                marketingAirlineDetails: {
                  display: "Alaska",
                  color: "#51172C",
                  code: "AS",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$347",
            },
            {
              departureFlight: {
                marketingAirline: "Alaska",
                operatingAirline: "Horizon Air As Alaskahorizon",
                fromTime: "5:10pm",
                toTime: "6:38pm",
                duration: "1h 28m",
                layovers: [],
                fromTimeDetails: {
                  hours: 17,
                  displayHours: 5,
                  minutes: 10,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 18,
                  displayHours: 6,
                  minutes: 38,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "Alaska",
                  color: "#51172C",
                  code: "AS",
                },
                operatingAirlineDetails: {
                  display: "Horizon Air As Alaskahorizon",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$350",
            },
            {
              departureFlight: {
                marketingAirline: "Alaska",
                operatingAirline: "Skywest Airlines As Alaskaskywest",
                fromTime: "10:30pm",
                toTime: "11:58pm",
                duration: "1h 28m",
                layovers: [],
                fromTimeDetails: {
                  hours: 22,
                  displayHours: 10,
                  minutes: 30,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 23,
                  displayHours: 11,
                  minutes: 58,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "Alaska",
                  color: "#51172C",
                  code: "AS",
                },
                operatingAirlineDetails: {
                  display: "Skywest Airlines As Alaskaskywest",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$350",
            },
            {
              departureFlight: {
                marketingAirline: "Multiple airlines",
                operatingAirline: "Skywest DBA United Express",
                fromTime: "10:30pm",
                toTime: "8:30am+1",
                duration: "10h 0m",
                layovers: [
                  {
                    fromTime: "10:30pm",
                    toTime: "11:14pm",
                    from: "SFO",
                    to: "SMF",
                    operatingAirline: "United       operated  by  Skywest  DBA  United  Express",
                    duration: "44m ",
                    fromTimeDetails: {
                      hours: 22,
                      displayHours: 10,
                      minutes: 30,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 23,
                      displayHours: 11,
                      minutes: 14,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    fromTime: "6:00am+1",
                    toTime: "6:39am",
                    from: "SMF",
                    to: "MCE",
                    operatingAirline: "Boutique  Air",
                    duration: "39m ",
                    fromTimeDetails: {
                      hours: 30,
                      displayHours: 6,
                      minutes: 0,
                      timeOfDay: "am",
                      excessDays: "+1",
                    },
                    toTimeDetails: {
                      hours: 6,
                      displayHours: 6,
                      minutes: 39,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                  {
                    fromTime: "7:10am",
                    toTime: "8:30am",
                    from: "MCE",
                    to: "LAX",
                    operatingAirline: "Boutique  Air",
                    duration: "1h 20m ",
                    fromTimeDetails: {
                      hours: 7,
                      displayHours: 7,
                      minutes: 10,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 8,
                      displayHours: 8,
                      minutes: 30,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                ],
                fromTimeDetails: {
                  hours: 22,
                  displayHours: 10,
                  minutes: 30,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 32,
                  displayHours: 8,
                  minutes: 30,
                  timeOfDay: "am",
                  excessDays: "+1",
                },
                marketingAirlineDetails: {
                  display: "Multiple airlines",
                  color: "#DFCCFB",
                },
                operatingAirlineDetails: {
                  display: "Skywest DBA United Express",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$351",
            },
            {
              departureFlight: {
                marketingAirline: "Multiple airlines",
                operatingAirline: "Skywest DBA United Express",
                fromTime: "10:30pm",
                toTime: "2:55pm+1",
                duration: "16h 25m",
                layovers: [
                  {
                    fromTime: "10:30pm",
                    toTime: "11:14pm",
                    from: "SFO",
                    to: "SMF",
                    operatingAirline: "United       operated  by  Skywest  DBA  United  Express",
                    duration: "44m ",
                    fromTimeDetails: {
                      hours: 22,
                      displayHours: 10,
                      minutes: 30,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 23,
                      displayHours: 11,
                      minutes: 14,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    fromTime: "6:00am+1",
                    toTime: "6:39am",
                    from: "SMF",
                    to: "MCE",
                    operatingAirline: "Boutique  Air",
                    duration: "39m ",
                    fromTimeDetails: {
                      hours: 30,
                      displayHours: 6,
                      minutes: 0,
                      timeOfDay: "am",
                      excessDays: "+1",
                    },
                    toTimeDetails: {
                      hours: 6,
                      displayHours: 6,
                      minutes: 39,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                  {
                    fromTime: "1:35pm",
                    toTime: "2:55pm",
                    from: "MCE",
                    to: "LAX",
                    operatingAirline: "Boutique  Air",
                    duration: "1h 20m ",
                    fromTimeDetails: {
                      hours: 13,
                      displayHours: 1,
                      minutes: 35,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 14,
                      displayHours: 2,
                      minutes: 55,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                ],
                fromTimeDetails: {
                  hours: 22,
                  displayHours: 10,
                  minutes: 30,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 38,
                  displayHours: 2,
                  minutes: 55,
                  timeOfDay: "pm",
                  excessDays: "+1",
                },
                marketingAirlineDetails: {
                  display: "Multiple airlines",
                  color: "#DFCCFB",
                },
                operatingAirlineDetails: {
                  display: "Skywest DBA United Express",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$357",
            },
            {
              departureFlight: {
                marketingAirline: "United",
                operatingAirline: "Skywest DBA United Express",
                fromTime: "8:30am",
                toTime: "9:48am",
                duration: "1h 18m",
                layovers: [],
                fromTimeDetails: {
                  hours: 8,
                  displayHours: 8,
                  minutes: 30,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 9,
                  displayHours: 9,
                  minutes: 48,
                  timeOfDay: "am",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "United",
                  color: "#235EA6",
                  code: "UA",
                },
                operatingAirlineDetails: {
                  display: "Skywest DBA United Express",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$369",
            },
            {
              departureFlight: {
                marketingAirline: "United",
                operatingAirline: null,
                fromTime: "6:50pm",
                toTime: "8:10pm",
                duration: "1h 20m",
                layovers: [],
                fromTimeDetails: {
                  hours: 18,
                  displayHours: 6,
                  minutes: 50,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 20,
                  displayHours: 8,
                  minutes: 10,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "United",
                  color: "#235EA6",
                  code: "UA",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$369",
            },
            {
              departureFlight: {
                marketingAirline: "United",
                operatingAirline: null,
                fromTime: "6:40pm",
                toTime: "8:07pm",
                duration: "1h 27m",
                layovers: [],
                fromTimeDetails: {
                  hours: 18,
                  displayHours: 6,
                  minutes: 40,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 20,
                  displayHours: 8,
                  minutes: 7,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "United",
                  color: "#235EA6",
                  code: "UA",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$369",
            },
            {
              departureFlight: {
                marketingAirline: "Alaska",
                operatingAirline: "Horizon Air As Alaskahorizon",
                fromTime: "6:25pm",
                toTime: "7:53pm",
                duration: "1h 28m",
                layovers: [],
                fromTimeDetails: {
                  hours: 18,
                  displayHours: 6,
                  minutes: 25,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 19,
                  displayHours: 7,
                  minutes: 53,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "Alaska",
                  color: "#51172C",
                  code: "AS",
                },
                operatingAirlineDetails: {
                  display: "Horizon Air As Alaskahorizon",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$449",
            },
            {
              departureFlight: {
                marketingAirline: "American",
                operatingAirline: "Skywest Airlines As American Eagle",
                fromTime: "12:28pm",
                toTime: "2:06pm",
                duration: "1h 38m",
                layovers: [],
                fromTimeDetails: {
                  hours: 12,
                  displayHours: 12,
                  minutes: 28,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 14,
                  displayHours: 2,
                  minutes: 6,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "American",
                  color: "#C5423E",
                  code: "AA",
                },
                operatingAirlineDetails: {
                  display: "Skywest Airlines As American Eagle",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$1,624",
            },
            {
              departureFlight: {
                marketingAirline: "American",
                operatingAirline: "Skywest Airlines As American Eagle",
                fromTime: "9:41pm",
                toTime: "11:21pm",
                duration: "1h 40m",
                layovers: [],
                fromTimeDetails: {
                  hours: 21,
                  displayHours: 9,
                  minutes: 41,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 23,
                  displayHours: 11,
                  minutes: 21,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "American",
                  color: "#C5423E",
                  code: "AA",
                },
                operatingAirlineDetails: {
                  display: "Skywest Airlines As American Eagle",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$1,624",
            },
            {
              departureFlight: {
                marketingAirline: "American",
                operatingAirline: "Skywest Airlines As American Eagle",
                fromTime: "5:09pm",
                toTime: "6:54pm",
                duration: "1h 45m",
                layovers: [],
                fromTimeDetails: {
                  hours: 17,
                  displayHours: 5,
                  minutes: 9,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 18,
                  displayHours: 6,
                  minutes: 54,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "American",
                  color: "#C5423E",
                  code: "AA",
                },
                operatingAirlineDetails: {
                  display: "Skywest Airlines As American Eagle",
                  color: "#DFCCFB",
                },
              },
              returnFlight: null,
              fare: "$1,624",
            },
            {
              departureFlight: {
                marketingAirline: "United",
                operatingAirline: null,
                layovers: [
                  {
                    from: "SFO",
                    fromTime: "11:00am",
                    duration: "1h 24m",
                    operatingAirline: "United",
                    to: "MFR",
                    toTime: "12:24pm",
                    fromTimeDetails: {
                      hours: 11,
                      displayHours: 11,
                      minutes: 0,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 12,
                      displayHours: 12,
                      minutes: 24,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    from: "MFR",
                    fromTime: "3:12pm",
                    duration: "2h",
                    operatingAirline: "United",
                    to: "LAX",
                    toTime: "5:12pm",
                    fromTimeDetails: {
                      hours: 15,
                      displayHours: 3,
                      minutes: 12,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 17,
                      displayHours: 5,
                      minutes: 12,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                ],
                duration: "6h12m",
                fromTime: "11:00am",
                toTime: "5:12pm",
                fromTimeDetails: {
                  hours: 11,
                  displayHours: 11,
                  minutes: 0,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 17,
                  displayHours: 5,
                  minutes: 12,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "United",
                  color: "#235EA6",
                  code: "UA",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$771",
            },
            {
              departureFlight: {
                marketingAirline: "American",
                operatingAirline: null,
                layovers: [
                  {
                    from: "SFO",
                    fromTime: "5:09pm",
                    duration: "2h 8m",
                    operatingAirline: "American",
                    to: "PHX",
                    toTime: "7:17pm",
                    fromTimeDetails: {
                      hours: 17,
                      displayHours: 5,
                      minutes: 9,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 19,
                      displayHours: 7,
                      minutes: 17,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    from: "PHX",
                    fromTime: "7:50pm",
                    duration: "1h 14m",
                    operatingAirline: "American",
                    to: "ABQ",
                    toTime: "10:04pm",
                    fromTimeDetails: {
                      hours: 19,
                      displayHours: 7,
                      minutes: 50,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 22,
                      displayHours: 10,
                      minutes: 4,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    from: "ABQ",
                    fromTime: "6:00am+1",
                    duration: "2h 5m",
                    operatingAirline: "American",
                    to: "LAX",
                    toTime: "7:05am",
                    fromTimeDetails: {
                      hours: 30,
                      displayHours: 6,
                      minutes: 0,
                      timeOfDay: "am",
                      excessDays: "+1",
                    },
                    toTimeDetails: {
                      hours: 7,
                      displayHours: 7,
                      minutes: 5,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                ],
                duration: "13h56m",
                fromTime: "5:09pm",
                toTime: "7:05am+1",
                fromTimeDetails: {
                  hours: 17,
                  displayHours: 5,
                  minutes: 9,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 31,
                  displayHours: 7,
                  minutes: 5,
                  timeOfDay: "am",
                  excessDays: "+1",
                },
                marketingAirlineDetails: {
                  display: "American",
                  color: "#C5423E",
                  code: "AA",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$785",
            },
            {
              departureFlight: {
                marketingAirline: "Multiple airlines",
                operatingAirline: null,
                layovers: [
                  {
                    from: "SFO",
                    fromTime: "1:10pm",
                    duration: "1h 48m",
                    operatingAirline: "United",
                    to: "PDX",
                    toTime: "2:58pm",
                    fromTimeDetails: {
                      hours: 13,
                      displayHours: 1,
                      minutes: 10,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 14,
                      displayHours: 2,
                      minutes: 58,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    from: "PDX",
                    fromTime: "5:03pm",
                    duration: "2h 19m",
                    operatingAirline: "Delta",
                    to: "LAX",
                    toTime: "7:22pm",
                    fromTimeDetails: {
                      hours: 17,
                      displayHours: 5,
                      minutes: 3,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 19,
                      displayHours: 7,
                      minutes: 22,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                ],
                duration: "6h12m",
                fromTime: "1:10pm",
                toTime: "7:22pm",
                fromTimeDetails: {
                  hours: 13,
                  displayHours: 1,
                  minutes: 10,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 19,
                  displayHours: 7,
                  minutes: 22,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "Multiple airlines",
                  color: "#DFCCFB",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$791",
            },
            {
              departureFlight: {
                marketingAirline: "American",
                operatingAirline: null,
                layovers: [
                  {
                    from: "SFO",
                    fromTime: "11:25pm",
                    duration: "4h 22m",
                    operatingAirline: "American",
                    to: "ORD",
                    toTime: "5:47am+1",
                    fromTimeDetails: {
                      hours: 23,
                      displayHours: 11,
                      minutes: 25,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 29,
                      displayHours: 5,
                      minutes: 47,
                      timeOfDay: "am",
                      excessDays: "+1",
                    },
                  },
                  {
                    from: "ORD",
                    fromTime: "12:06pm",
                    duration: "4h 33m",
                    operatingAirline: "American",
                    to: "SEA",
                    toTime: "2:39pm",
                    fromTimeDetails: {
                      hours: 12,
                      displayHours: 12,
                      minutes: 6,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 14,
                      displayHours: 2,
                      minutes: 39,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    from: "SEA",
                    fromTime: "7:35pm",
                    duration: "3h",
                    operatingAirline: "American",
                    to: "LAX",
                    toTime: "10:35pm",
                    fromTimeDetails: {
                      hours: 19,
                      displayHours: 7,
                      minutes: 35,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 22,
                      displayHours: 10,
                      minutes: 35,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                ],
                duration: "23h10m",
                fromTime: "11:25pm",
                toTime: "10:35pm+1",
                fromTimeDetails: {
                  hours: 23,
                  displayHours: 11,
                  minutes: 25,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 46,
                  displayHours: 10,
                  minutes: 35,
                  timeOfDay: "pm",
                  excessDays: "+1",
                },
                marketingAirlineDetails: {
                  display: "American",
                  color: "#C5423E",
                  code: "AA",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$793",
            },
            {
              departureFlight: {
                marketingAirline: "Multiple airlines",
                operatingAirline: null,
                layovers: [
                  {
                    from: "SFO",
                    fromTime: "11:58pm",
                    duration: "5h 12m",
                    operatingAirline: "American",
                    to: "CLT",
                    toTime: "8:10am+1",
                    fromTimeDetails: {
                      hours: 23,
                      displayHours: 11,
                      minutes: 58,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 32,
                      displayHours: 8,
                      minutes: 10,
                      timeOfDay: "am",
                      excessDays: "+1",
                    },
                  },
                  {
                    from: "CLT",
                    fromTime: "9:16am",
                    duration: "2h 12m",
                    operatingAirline: "American",
                    to: "ORD",
                    toTime: "10:28am",
                    fromTimeDetails: {
                      hours: 9,
                      displayHours: 9,
                      minutes: 16,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 10,
                      displayHours: 10,
                      minutes: 28,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                  {
                    from: "ORD",
                    fromTime: "12:45pm",
                    duration: "4h 10m",
                    operatingAirline: "United",
                    to: "LAX",
                    toTime: "2:55pm",
                    fromTimeDetails: {
                      hours: 12,
                      displayHours: 12,
                      minutes: 45,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 14,
                      displayHours: 2,
                      minutes: 55,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                ],
                duration: "14h57m",
                fromTime: "11:58pm",
                toTime: "2:55pm+1",
                fromTimeDetails: {
                  hours: 23,
                  displayHours: 11,
                  minutes: 58,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 38,
                  displayHours: 2,
                  minutes: 55,
                  timeOfDay: "pm",
                  excessDays: "+1",
                },
                marketingAirlineDetails: {
                  display: "Multiple airlines",
                  color: "#DFCCFB",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$802",
            },
            {
              departureFlight: {
                marketingAirline: "Alaska",
                operatingAirline: null,
                layovers: [
                  {
                    from: "SFO",
                    fromTime: "10:00pm",
                    duration: "1h 51m",
                    operatingAirline: "Alaska",
                    to: "PDX",
                    toTime: "11:51pm",
                    fromTimeDetails: {
                      hours: 22,
                      displayHours: 10,
                      minutes: 0,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 23,
                      displayHours: 11,
                      minutes: 51,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    from: "PDX",
                    fromTime: "8:05am+1",
                    duration: "2h 25m",
                    operatingAirline: "Alaska",
                    to: "LAX",
                    toTime: "10:30am",
                    fromTimeDetails: {
                      hours: 32,
                      displayHours: 8,
                      minutes: 5,
                      timeOfDay: "am",
                      excessDays: "+1",
                    },
                    toTimeDetails: {
                      hours: 10,
                      displayHours: 10,
                      minutes: 30,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                ],
                duration: "12h30m",
                fromTime: "10:00pm",
                toTime: "10:30am+1",
                fromTimeDetails: {
                  hours: 22,
                  displayHours: 10,
                  minutes: 0,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 34,
                  displayHours: 10,
                  minutes: 30,
                  timeOfDay: "am",
                  excessDays: "+1",
                },
                marketingAirlineDetails: {
                  display: "Alaska",
                  color: "#51172C",
                  code: "AS",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$818",
            },
            {
              departureFlight: {
                marketingAirline: "American",
                operatingAirline: null,
                layovers: [
                  {
                    from: "SFO",
                    fromTime: "6:25am",
                    duration: "2h 12m",
                    operatingAirline: "American",
                    to: "PHX",
                    toTime: "8:37am",
                    fromTimeDetails: {
                      hours: 6,
                      displayHours: 6,
                      minutes: 25,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 8,
                      displayHours: 8,
                      minutes: 37,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                  {
                    from: "PHX",
                    fromTime: "9:40am",
                    duration: "1h 22m",
                    operatingAirline: "American",
                    to: "ABQ",
                    toTime: "12:02pm",
                    fromTimeDetails: {
                      hours: 9,
                      displayHours: 9,
                      minutes: 40,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 12,
                      displayHours: 12,
                      minutes: 2,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    from: "ABQ",
                    fromTime: "1:16pm",
                    duration: "2h 7m",
                    operatingAirline: "American",
                    to: "LAX",
                    toTime: "2:23pm",
                    fromTimeDetails: {
                      hours: 13,
                      displayHours: 1,
                      minutes: 16,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 14,
                      displayHours: 2,
                      minutes: 23,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                ],
                duration: "7h58m",
                fromTime: "6:25am",
                toTime: "2:23pm",
                fromTimeDetails: {
                  hours: 6,
                  displayHours: 6,
                  minutes: 25,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 14,
                  displayHours: 2,
                  minutes: 23,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "American",
                  color: "#C5423E",
                  code: "AA",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$821",
            },
            {
              departureFlight: {
                marketingAirline: "United",
                operatingAirline: null,
                layovers: [
                  {
                    from: "SFO",
                    fromTime: "10:50am",
                    duration: "2h 32m",
                    operatingAirline: "United",
                    to: "DEN",
                    toTime: "2:22pm",
                    fromTimeDetails: {
                      hours: 10,
                      displayHours: 10,
                      minutes: 50,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 14,
                      displayHours: 2,
                      minutes: 22,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    from: "DEN",
                    fromTime: "4:05pm",
                    duration: "2h 19m",
                    operatingAirline: "United",
                    to: "LAX",
                    toTime: "5:24pm",
                    fromTimeDetails: {
                      hours: 16,
                      displayHours: 4,
                      minutes: 5,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 17,
                      displayHours: 5,
                      minutes: 24,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                ],
                duration: "6h34m",
                fromTime: "10:50am",
                toTime: "5:24pm",
                fromTimeDetails: {
                  hours: 10,
                  displayHours: 10,
                  minutes: 50,
                  timeOfDay: "am",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 17,
                  displayHours: 5,
                  minutes: 24,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                marketingAirlineDetails: {
                  display: "United",
                  color: "#235EA6",
                  code: "UA",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$822",
            },
            {
              departureFlight: {
                marketingAirline: "Multiple airlines",
                operatingAirline: null,
                layovers: [
                  {
                    from: "SFO",
                    fromTime: "11:55pm",
                    duration: "3h 39m",
                    operatingAirline: "United",
                    to: "IAH",
                    toTime: "5:34am+1",
                    fromTimeDetails: {
                      hours: 23,
                      displayHours: 11,
                      minutes: 55,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 29,
                      displayHours: 5,
                      minutes: 34,
                      timeOfDay: "am",
                      excessDays: "+1",
                    },
                  },
                  {
                    from: "IAH",
                    fromTime: "8:13am",
                    duration: "1h 22m",
                    operatingAirline: "American",
                    to: "DFW",
                    toTime: "9:35am",
                    fromTimeDetails: {
                      hours: 8,
                      displayHours: 8,
                      minutes: 13,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 9,
                      displayHours: 9,
                      minutes: 35,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                  {
                    from: "DFW",
                    fromTime: "10:30am",
                    duration: "3h 16m",
                    operatingAirline: "American",
                    to: "LAX",
                    toTime: "11:46am",
                    fromTimeDetails: {
                      hours: 10,
                      displayHours: 10,
                      minutes: 30,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 11,
                      displayHours: 11,
                      minutes: 46,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                ],
                duration: "11h51m",
                fromTime: "11:55pm",
                toTime: "11:46am+1",
                fromTimeDetails: {
                  hours: 23,
                  displayHours: 11,
                  minutes: 55,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 35,
                  displayHours: 11,
                  minutes: 46,
                  timeOfDay: "am",
                  excessDays: "+1",
                },
                marketingAirlineDetails: {
                  display: "Multiple airlines",
                  color: "#DFCCFB",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$889",
            },
            {
              departureFlight: {
                marketingAirline: "Alaska",
                operatingAirline: null,
                layovers: [
                  {
                    from: "SFO",
                    fromTime: "1:50pm",
                    duration: "2h 5m",
                    operatingAirline: "Alaska",
                    to: "GEG",
                    toTime: "3:55pm",
                    fromTimeDetails: {
                      hours: 13,
                      displayHours: 1,
                      minutes: 50,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                    toTimeDetails: {
                      hours: 15,
                      displayHours: 3,
                      minutes: 55,
                      timeOfDay: "pm",
                      excessDays: null,
                    },
                  },
                  {
                    from: "GEG",
                    fromTime: "6:00am+1",
                    duration: "2h 40m",
                    operatingAirline: "Alaska",
                    to: "LAX",
                    toTime: "8:40am",
                    fromTimeDetails: {
                      hours: 30,
                      displayHours: 6,
                      minutes: 0,
                      timeOfDay: "am",
                      excessDays: "+1",
                    },
                    toTimeDetails: {
                      hours: 8,
                      displayHours: 8,
                      minutes: 40,
                      timeOfDay: "am",
                      excessDays: null,
                    },
                  },
                ],
                duration: "18h50m",
                fromTime: "1:50pm",
                toTime: "8:40am+1",
                fromTimeDetails: {
                  hours: 13,
                  displayHours: 1,
                  minutes: 50,
                  timeOfDay: "pm",
                  excessDays: null,
                },
                toTimeDetails: {
                  hours: 32,
                  displayHours: 8,
                  minutes: 40,
                  timeOfDay: "am",
                  excessDays: "+1",
                },
                marketingAirlineDetails: {
                  display: "Alaska",
                  color: "#51172C",
                  code: "AS",
                },
                operatingAirlineDetails: {},
              },
              returnFlight: null,
              fare: "$929",
            },
          ]}
          formData={{
            from: "SFO",
            to: "DEN",
            fromDate: "2021-11-03",
            toDate: "2021-11-05",
            numPax: 1,
            roundtrip: false,
            cabin: "econ",
            searchByPoints: false,
          }}
        />
      </Box>
    </BumbagProvider>,
    root,
  );
}
